/**
 * AUTO-GENERATED by scripts/generate-svg-manifest.mjs — DO NOT EDIT BY HAND.
 * Re-run `npm run svg:manifest` (from the monorepo lane) after adding icons.
 * 162 icons across 8 source groups.
 * Skipped: library/FacebookIframe
 */
import type { ComponentType } from "react";
import I0 from "@/app/components/icons/ArchiveIcon";
import I1 from "@/app/components/icons/ArrowRightIcon";
import I2 from "@/app/components/icons/AttachIcon";
import I3 from "@/app/components/icons/AvatarIcon";
import I4 from "@/app/components/icons/BanIcon";
import I5 from "@/app/components/icons/BankIcon";
import I6 from "@/app/components/icons/CancelIcon";
import I7 from "@/app/components/icons/CashIcon";
import I8 from "@/app/components/icons/ChartIcon";
import I9 from "@/app/components/icons/ChatIcon";
import I10 from "@/app/components/icons/CheckIcon";
import I11 from "@/app/components/icons/CloudIcon";
import I12 from "@/app/components/icons/ContactIcon";
import I13 from "@/app/components/icons/ConvertImageIcon";
import I14 from "@/app/components/icons/ConvertVideoIcon";
import I15 from "@/app/components/icons/CopyIcon";
import I16 from "@/app/components/icons/DTogExpandIcon";
import I17 from "@/app/components/icons/DatabaseIcon";
import I18 from "@/app/components/icons/DeployIcon";
import I19 from "@/app/components/icons/DownloadIcon";
import I20 from "@/app/components/icons/DrawerAlertsIcon";
import I21 from "@/app/components/icons/DrawerChatsIcon";
import I22 from "@/app/components/icons/DrawerFrontDeskIcon";
import I23 from "@/app/components/icons/DrawerInboxIcon";
import I24 from "@/app/components/icons/DrawerSessionsIcon";
import I25 from "@/app/components/icons/EditIcon";
import I26 from "@/app/components/icons/EditorIcon";
import I27 from "@/app/components/icons/EventIcon";
import I28 from "@/app/components/icons/EyeIcon";
import I29 from "@/app/components/icons/FileIcon";
import I30 from "@/app/components/icons/GlobeIcon";
import I31 from "@/app/components/icons/GraduationIcon";
import I32 from "@/app/components/icons/LogsIcon";
import I33 from "@/app/components/icons/LotusIcon";
import I34 from "@/app/components/icons/MembersIcon";
import I35 from "@/app/components/icons/MicIcon";
import I36 from "@/app/components/icons/ModulesIcon";
import I37 from "@/app/components/icons/MoreIcon";
import I38 from "@/app/components/icons/PauseIcon";
import I39 from "@/app/components/icons/PaypalIcon";
import I40 from "@/app/components/icons/PhoneIcon";
import I41 from "@/app/components/icons/PhotosIcon";
import I42 from "@/app/components/icons/PlayIcon";
import I43 from "@/app/components/icons/PollIcon";
import I44 from "@/app/components/icons/ProcessesIcon";
import I45 from "@/app/components/icons/RecordIcon";
import I46 from "@/app/components/icons/ReplyIcon";
import I47 from "@/app/components/icons/SaveIcon";
import I48 from "@/app/components/icons/SearchIcon";
import I49 from "@/app/components/icons/SendIcon";
import I50 from "@/app/components/icons/SettingsIcon";
import I51 from "@/app/components/icons/ShieldIcon";
import I52 from "@/app/components/icons/SmileIcon";
import I53 from "@/app/components/icons/StarIcon";
import I54 from "@/app/components/icons/StopIcon";
import I55 from "@/app/components/icons/StorageIcon";
import I56 from "@/app/components/icons/SuggestionIcon";
import I57 from "@/app/components/icons/SyncIcon";
import I58 from "@/app/components/icons/TargetIcon";
import I59 from "@/app/components/icons/TrashIcon";
import I60 from "@/app/components/icons/UploadCloudIcon";
import I61 from "@/app/components/icons/UtilsIcon";
import I62 from "@/app/components/icons/VideoIcon";
import I63 from "@/app/components/icons/WalletIcon";
import I64 from "@/app/components/icons/WaveformIcon";
import I65 from "@/app/components/LibraryIcon";
import I66 from "@/app/components/sandbox/SandboxIcon";
import I67 from "@/app/components/claude/ClaudeIcon";
import { IconInvoice as I68 } from "@tgv/module-component-library/components/icons/AccountIcon";
import { IconAnalytics as I69 } from "@tgv/module-component-library/components/icons/AnalyticsIcon";
import { BodyOutlineIcon as I70 } from "@tgv/module-component-library/components/icons/BodyGraphIcon";
import { IconBook as I71 } from "@tgv/module-component-library/components/icons/BookIcon";
import { IconCalendar as I72 } from "@tgv/module-component-library/components/icons/CalendarIcon";
import { IconCart as I73 } from "@tgv/module-component-library/components/icons/CartIcon";
import { IconCourse as I74 } from "@tgv/module-component-library/components/icons/CourseIcon";
import { IconCreditCard as I75 } from "@tgv/module-component-library/components/icons/CreditCardIcon";
import { IconEditor as I76 } from "@tgv/module-component-library/components/icons/EditorIcon";
import { IconEmail as I77 } from "@tgv/module-component-library/components/icons/EmailIcon";
import { IconHome as I78 } from "@tgv/module-component-library/components/icons/HomeIcon";
import { IconArrowCircle as I79 } from "@tgv/module-component-library/components/icons/IconArrowCircle";
import { IconLock as I80 } from "@tgv/module-component-library/components/icons/IconLock";
import { IconTrash as I81 } from "@tgv/module-component-library/components/icons/IconTrash";
import I82 from "@tgv/module-component-library/components/icons/LeafIcon";
import I83 from "@tgv/module-component-library/components/icons/LeaveIcon";
import { IconLifeRing as I84 } from "@tgv/module-component-library/components/icons/LifeRingIcon";
import { IconMegaphone as I85 } from "@tgv/module-component-library/components/icons/MegaphoneIcon";
import { IconMembers as I86 } from "@tgv/module-component-library/components/icons/MembersIcon";
import { IconPayouts as I87 } from "@tgv/module-component-library/components/icons/PayoutsIcon";
import { IconSearch as I88 } from "@tgv/module-component-library/components/icons/SearchIcon";
import { IconServicesBell as I89 } from "@tgv/module-component-library/components/icons/ServicesIcon";
import { IconSessions as I90 } from "@tgv/module-component-library/components/icons/SessionsIcon";
import { IconSettings as I91 } from "@tgv/module-component-library/components/icons/SettingsIcon";
import I92 from "@tgv/module-component-library/components/icons/SignOutIcon";
import { IconStorage as I93 } from "@tgv/module-component-library/components/icons/StorageIcon";
import { IconStorefront as I94 } from "@tgv/module-component-library/components/icons/StorefrontIcon";
import { IconSubscription as I95 } from "@tgv/module-component-library/components/icons/SubscriptionIcon";
import { IconUser as I96 } from "@tgv/module-component-library/components/icons/UserIcon";
import { IconWallet as I97 } from "@tgv/module-component-library/components/icons/WalletIcon";
import I98 from "@tgv/module-component-library/components/icons/facebook/FacebookIcon";
import { WebsiteBuilderIcon as I99 } from "@tgv/module-component-library/components/tgv-v5";
import { BookingsIcon as I100 } from "@tgv/module-component-library/components/tgv-v5";
import { MeetingsIcon as I101 } from "@tgv/module-component-library/components/tgv-v5";
import { PaymentsIcon as I102 } from "@tgv/module-component-library/components/tgv-v5";
import { ClientDashboardIcon as I103 } from "@tgv/module-component-library/components/tgv-v5";
import { CustomWebsitesIcon as I104 } from "@tgv/module-component-library/components/tgv-v5";
import { MagnifierIcon as I105 } from "@tgv/module-video-calls/meetings/stage/icons";
import { WaitingRoomIcon as I106 } from "@tgv/module-video-calls/meetings/stage/icons";
import { MoreIcon as I107 } from "@tgv/module-video-calls/meetings/stage/icons";
import { PinIcon as I108 } from "@tgv/module-video-calls/meetings/stage/icons";
import { SwitchScreenIcon as I109 } from "@tgv/module-video-calls/meetings/stage/icons";
import { SelfViewIcon as I110 } from "@tgv/module-video-calls/meetings/stage/icons";
import { SpeakerViewIcon as I111 } from "@tgv/module-video-calls/meetings/stage/icons";
import { GalleryViewIcon as I112 } from "@tgv/module-video-calls/meetings/stage/icons";
import { CloseIcon as I113 } from "@tgv/module-video-calls/meetings/stage/icons";
import { ChevronIcon as I114 } from "@tgv/module-video-calls/meetings/stage/icons";
import { ChevronLeftIcon as I115 } from "@tgv/module-video-calls/meetings/stage/icons";
import { ChevronRightIcon as I116 } from "@tgv/module-video-calls/meetings/stage/icons";
import { FullscreenIcon as I117 } from "@tgv/module-video-calls/meetings/stage/icons";
import { ExitFullscreenIcon as I118 } from "@tgv/module-video-calls/meetings/stage/icons";
import { PopOutIcon as I119 } from "@tgv/module-video-calls/meetings/stage/icons";
import { RecordIcon as I120 } from "@tgv/module-video-calls/meetings/stage/icons";
import { StopIcon as I121 } from "@tgv/module-video-calls/meetings/stage/icons";
import { LinkIcon as I122 } from "@tgv/module-video-calls/meetings/stage/icons";
import { EndCallIcon as I123 } from "@tgv/module-video-calls/meetings/stage/icons";
import { LeaveIcon as I124 } from "@tgv/module-video-calls/meetings/stage/icons";
import { ChatIcon as I125 } from "@tgv/module-video-calls/meetings/stage/icons";
import { PeopleIcon as I126 } from "@tgv/module-video-calls/meetings/stage/icons";
import { BreakoutIcon as I127 } from "@tgv/module-video-calls/meetings/stage/icons";
import { TimerIcon as I128 } from "@tgv/module-video-calls/meetings/stage/icons";
import { GearIcon as I129 } from "@tgv/module-video-calls/meetings/stage/icons";
import { SendIcon as I130 } from "@tgv/module-video-calls/meetings/stage/icons";
import I131 from "@tgv/module-video-calls/_icons/LeaveIcon";
import { IconDesktop as I132 } from "@tgv/module-page-editor/editor/page-editor/toolbar/EditorToolbar.icons";
import { IconMobile as I133 } from "@tgv/module-page-editor/editor/page-editor/toolbar/EditorToolbar.icons";
import { IconUndo as I134 } from "@tgv/module-page-editor/editor/page-editor/toolbar/EditorToolbar.icons";
import { IconRedo as I135 } from "@tgv/module-page-editor/editor/page-editor/toolbar/EditorToolbar.icons";
import { IconDots as I136 } from "@tgv/module-page-editor/editor/page-editor/toolbar/EditorToolbar.icons";
import { IconEye as I137 } from "@tgv/module-page-editor/editor/page-editor/toolbar/EditorToolbar.icons";
import { IconKeyboard as I138 } from "@tgv/module-page-editor/editor/page-editor/toolbar/EditorToolbar.icons";
import { IconSupport as I139 } from "@tgv/module-page-editor/editor/page-editor/toolbar/EditorToolbar.icons";
import { IconReset as I140 } from "@tgv/module-page-editor/editor/page-editor/toolbar/EditorToolbar.icons";
import { IconResetToPublished as I141 } from "@tgv/module-page-editor/editor/page-editor/toolbar/EditorToolbar.icons";
import { IconFullScreen as I142 } from "@tgv/module-page-editor/editor/page-editor/toolbar/EditorToolbar.icons";
import { IconNoEntry as I143 } from "@tgv/module-page-editor/editor/page-editor/toolbar/EditorToolbar.icons";
import { IconTrash as I144 } from "@tgv/module-page-editor/editor/page-editor/toolbar/EditorToolbar.icons";
import { IconEyeOff as I145 } from "@tgv/module-page-editor/editor/page-editor/toolbar/EditorToolbar.icons";
import { IconReset as I146 } from "@tgv/module-page-editor/editor/paint/icons";
import { IconCopy as I147 } from "@tgv/module-page-editor/editor/paint/icons";
import { IconPaste as I148 } from "@tgv/module-page-editor/editor/paint/icons";
import { IconPlus as I149 } from "@tgv/module-page-editor/editor/paint/icons";
import { IconTrash as I150 } from "@tgv/module-page-editor/editor/paint/icons";
import { IconEye as I151 } from "@tgv/module-page-editor/editor/paint/icons";
import { IconEyeOff as I152 } from "@tgv/module-page-editor/editor/paint/icons";
import { IconLock as I153 } from "@tgv/module-page-editor/editor/paint/icons";
import { IconUnlock as I154 } from "@tgv/module-page-editor/editor/paint/icons";
import { LinkIcon as I155 } from "@tgv/module-page-editor/editor/component-library/marketing/link-tools/shared/icons";
import { QRIcon as I156 } from "@tgv/module-page-editor/editor/component-library/marketing/link-tools/shared/icons";
import { CopyIcon as I157 } from "@tgv/module-page-editor/editor/component-library/marketing/link-tools/shared/icons";
import { TrashIcon as I158 } from "@tgv/module-page-editor/editor/component-library/marketing/link-tools/shared/icons";
import { EditIcon as I159 } from "@tgv/module-page-editor/editor/component-library/marketing/link-tools/shared/icons";
import { CloseIcon as I160 } from "@tgv/module-page-editor/editor/component-library/marketing/link-tools/shared/icons";
import { DownloadIcon as I161 } from "@tgv/module-page-editor/editor/component-library/marketing/link-tools/shared/icons";

// Icon components have heterogeneous prop shapes ({size?} & SVGProps etc.) — the
// lab renders them bare and edits serialized output, so props are irrelevant here.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type SvgLabComponent = ComponentType<any>;

export type SvgManifestEntry = {
  key: string;
  name: string;
  source: string;
  sourceLabel: string;
  importPath: string;
  Comp: SvgLabComponent;
};

export const SVG_MANIFEST: SvgManifestEntry[] = [
  { key: "office/ArchiveIcon", name: "ArchiveIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/ArchiveIcon", Comp: I0 },
  { key: "office/ArrowRightIcon", name: "ArrowRightIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/ArrowRightIcon", Comp: I1 },
  { key: "office/AttachIcon", name: "AttachIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/AttachIcon", Comp: I2 },
  { key: "office/AvatarIcon", name: "AvatarIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/AvatarIcon", Comp: I3 },
  { key: "office/BanIcon", name: "BanIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/BanIcon", Comp: I4 },
  { key: "office/BankIcon", name: "BankIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/BankIcon", Comp: I5 },
  { key: "office/CancelIcon", name: "CancelIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/CancelIcon", Comp: I6 },
  { key: "office/CashIcon", name: "CashIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/CashIcon", Comp: I7 },
  { key: "office/ChartIcon", name: "ChartIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/ChartIcon", Comp: I8 },
  { key: "office/ChatIcon", name: "ChatIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/ChatIcon", Comp: I9 },
  { key: "office/CheckIcon", name: "CheckIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/CheckIcon", Comp: I10 },
  { key: "office/CloudIcon", name: "CloudIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/CloudIcon", Comp: I11 },
  { key: "office/ContactIcon", name: "ContactIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/ContactIcon", Comp: I12 },
  { key: "office/ConvertImageIcon", name: "ConvertImageIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/ConvertImageIcon", Comp: I13 },
  { key: "office/ConvertVideoIcon", name: "ConvertVideoIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/ConvertVideoIcon", Comp: I14 },
  { key: "office/CopyIcon", name: "CopyIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/CopyIcon", Comp: I15 },
  { key: "office/DTogExpandIcon", name: "DTogExpandIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/DTogExpandIcon", Comp: I16 },
  { key: "office/DatabaseIcon", name: "DatabaseIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/DatabaseIcon", Comp: I17 },
  { key: "office/DeployIcon", name: "DeployIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/DeployIcon", Comp: I18 },
  { key: "office/DownloadIcon", name: "DownloadIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/DownloadIcon", Comp: I19 },
  { key: "office/DrawerAlertsIcon", name: "DrawerAlertsIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/DrawerAlertsIcon", Comp: I20 },
  { key: "office/DrawerChatsIcon", name: "DrawerChatsIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/DrawerChatsIcon", Comp: I21 },
  { key: "office/DrawerFrontDeskIcon", name: "DrawerFrontDeskIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/DrawerFrontDeskIcon", Comp: I22 },
  { key: "office/DrawerInboxIcon", name: "DrawerInboxIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/DrawerInboxIcon", Comp: I23 },
  { key: "office/DrawerSessionsIcon", name: "DrawerSessionsIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/DrawerSessionsIcon", Comp: I24 },
  { key: "office/EditIcon", name: "EditIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/EditIcon", Comp: I25 },
  { key: "office/EditorIcon", name: "EditorIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/EditorIcon", Comp: I26 },
  { key: "office/EventIcon", name: "EventIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/EventIcon", Comp: I27 },
  { key: "office/EyeIcon", name: "EyeIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/EyeIcon", Comp: I28 },
  { key: "office/FileIcon", name: "FileIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/FileIcon", Comp: I29 },
  { key: "office/GlobeIcon", name: "GlobeIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/GlobeIcon", Comp: I30 },
  { key: "office/GraduationIcon", name: "GraduationIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/GraduationIcon", Comp: I31 },
  { key: "office/LogsIcon", name: "LogsIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/LogsIcon", Comp: I32 },
  { key: "office/LotusIcon", name: "LotusIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/LotusIcon", Comp: I33 },
  { key: "office/MembersIcon", name: "MembersIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/MembersIcon", Comp: I34 },
  { key: "office/MicIcon", name: "MicIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/MicIcon", Comp: I35 },
  { key: "office/ModulesIcon", name: "ModulesIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/ModulesIcon", Comp: I36 },
  { key: "office/MoreIcon", name: "MoreIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/MoreIcon", Comp: I37 },
  { key: "office/PauseIcon", name: "PauseIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/PauseIcon", Comp: I38 },
  { key: "office/PaypalIcon", name: "PaypalIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/PaypalIcon", Comp: I39 },
  { key: "office/PhoneIcon", name: "PhoneIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/PhoneIcon", Comp: I40 },
  { key: "office/PhotosIcon", name: "PhotosIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/PhotosIcon", Comp: I41 },
  { key: "office/PlayIcon", name: "PlayIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/PlayIcon", Comp: I42 },
  { key: "office/PollIcon", name: "PollIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/PollIcon", Comp: I43 },
  { key: "office/ProcessesIcon", name: "ProcessesIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/ProcessesIcon", Comp: I44 },
  { key: "office/RecordIcon", name: "RecordIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/RecordIcon", Comp: I45 },
  { key: "office/ReplyIcon", name: "ReplyIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/ReplyIcon", Comp: I46 },
  { key: "office/SaveIcon", name: "SaveIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/SaveIcon", Comp: I47 },
  { key: "office/SearchIcon", name: "SearchIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/SearchIcon", Comp: I48 },
  { key: "office/SendIcon", name: "SendIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/SendIcon", Comp: I49 },
  { key: "office/SettingsIcon", name: "SettingsIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/SettingsIcon", Comp: I50 },
  { key: "office/ShieldIcon", name: "ShieldIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/ShieldIcon", Comp: I51 },
  { key: "office/SmileIcon", name: "SmileIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/SmileIcon", Comp: I52 },
  { key: "office/StarIcon", name: "StarIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/StarIcon", Comp: I53 },
  { key: "office/StopIcon", name: "StopIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/StopIcon", Comp: I54 },
  { key: "office/StorageIcon", name: "StorageIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/StorageIcon", Comp: I55 },
  { key: "office/SuggestionIcon", name: "SuggestionIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/SuggestionIcon", Comp: I56 },
  { key: "office/SyncIcon", name: "SyncIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/SyncIcon", Comp: I57 },
  { key: "office/TargetIcon", name: "TargetIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/TargetIcon", Comp: I58 },
  { key: "office/TrashIcon", name: "TrashIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/TrashIcon", Comp: I59 },
  { key: "office/UploadCloudIcon", name: "UploadCloudIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/UploadCloudIcon", Comp: I60 },
  { key: "office/UtilsIcon", name: "UtilsIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/UtilsIcon", Comp: I61 },
  { key: "office/VideoIcon", name: "VideoIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/VideoIcon", Comp: I62 },
  { key: "office/WalletIcon", name: "WalletIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/WalletIcon", Comp: I63 },
  { key: "office/WaveformIcon", name: "WaveformIcon", source: "office", sourceLabel: "Office icons", importPath: "@/app/components/icons/WaveformIcon", Comp: I64 },
  { key: "office-brand/LibraryIcon", name: "LibraryIcon", source: "office-brand", sourceLabel: "Office brand", importPath: "@/app/components/LibraryIcon", Comp: I65 },
  { key: "office-brand/SandboxIcon", name: "SandboxIcon", source: "office-brand", sourceLabel: "Office brand", importPath: "@/app/components/sandbox/SandboxIcon", Comp: I66 },
  { key: "office-brand/ClaudeIcon", name: "ClaudeIcon", source: "office-brand", sourceLabel: "Office brand", importPath: "@/app/components/claude/ClaudeIcon", Comp: I67 },
  { key: "library/IconInvoice", name: "IconInvoice", source: "library", sourceLabel: "Component Library", importPath: "@tgv/module-component-library/components/icons/AccountIcon", Comp: I68 },
  { key: "library/IconAnalytics", name: "IconAnalytics", source: "library", sourceLabel: "Component Library", importPath: "@tgv/module-component-library/components/icons/AnalyticsIcon", Comp: I69 },
  { key: "library/BodyOutlineIcon", name: "BodyOutlineIcon", source: "library", sourceLabel: "Component Library", importPath: "@tgv/module-component-library/components/icons/BodyGraphIcon", Comp: I70 },
  { key: "library/IconBook", name: "IconBook", source: "library", sourceLabel: "Component Library", importPath: "@tgv/module-component-library/components/icons/BookIcon", Comp: I71 },
  { key: "library/IconCalendar", name: "IconCalendar", source: "library", sourceLabel: "Component Library", importPath: "@tgv/module-component-library/components/icons/CalendarIcon", Comp: I72 },
  { key: "library/IconCart", name: "IconCart", source: "library", sourceLabel: "Component Library", importPath: "@tgv/module-component-library/components/icons/CartIcon", Comp: I73 },
  { key: "library/IconCourse", name: "IconCourse", source: "library", sourceLabel: "Component Library", importPath: "@tgv/module-component-library/components/icons/CourseIcon", Comp: I74 },
  { key: "library/IconCreditCard", name: "IconCreditCard", source: "library", sourceLabel: "Component Library", importPath: "@tgv/module-component-library/components/icons/CreditCardIcon", Comp: I75 },
  { key: "library/IconEditor", name: "IconEditor", source: "library", sourceLabel: "Component Library", importPath: "@tgv/module-component-library/components/icons/EditorIcon", Comp: I76 },
  { key: "library/IconEmail", name: "IconEmail", source: "library", sourceLabel: "Component Library", importPath: "@tgv/module-component-library/components/icons/EmailIcon", Comp: I77 },
  { key: "library/IconHome", name: "IconHome", source: "library", sourceLabel: "Component Library", importPath: "@tgv/module-component-library/components/icons/HomeIcon", Comp: I78 },
  { key: "library/IconArrowCircle", name: "IconArrowCircle", source: "library", sourceLabel: "Component Library", importPath: "@tgv/module-component-library/components/icons/IconArrowCircle", Comp: I79 },
  { key: "library/IconLock", name: "IconLock", source: "library", sourceLabel: "Component Library", importPath: "@tgv/module-component-library/components/icons/IconLock", Comp: I80 },
  { key: "library/IconTrash", name: "IconTrash", source: "library", sourceLabel: "Component Library", importPath: "@tgv/module-component-library/components/icons/IconTrash", Comp: I81 },
  { key: "library/LeafIcon", name: "LeafIcon", source: "library", sourceLabel: "Component Library", importPath: "@tgv/module-component-library/components/icons/LeafIcon", Comp: I82 },
  { key: "library/LeaveIcon", name: "LeaveIcon", source: "library", sourceLabel: "Component Library", importPath: "@tgv/module-component-library/components/icons/LeaveIcon", Comp: I83 },
  { key: "library/IconLifeRing", name: "IconLifeRing", source: "library", sourceLabel: "Component Library", importPath: "@tgv/module-component-library/components/icons/LifeRingIcon", Comp: I84 },
  { key: "library/IconMegaphone", name: "IconMegaphone", source: "library", sourceLabel: "Component Library", importPath: "@tgv/module-component-library/components/icons/MegaphoneIcon", Comp: I85 },
  { key: "library/IconMembers", name: "IconMembers", source: "library", sourceLabel: "Component Library", importPath: "@tgv/module-component-library/components/icons/MembersIcon", Comp: I86 },
  { key: "library/IconPayouts", name: "IconPayouts", source: "library", sourceLabel: "Component Library", importPath: "@tgv/module-component-library/components/icons/PayoutsIcon", Comp: I87 },
  { key: "library/IconSearch", name: "IconSearch", source: "library", sourceLabel: "Component Library", importPath: "@tgv/module-component-library/components/icons/SearchIcon", Comp: I88 },
  { key: "library/IconServicesBell", name: "IconServicesBell", source: "library", sourceLabel: "Component Library", importPath: "@tgv/module-component-library/components/icons/ServicesIcon", Comp: I89 },
  { key: "library/IconSessions", name: "IconSessions", source: "library", sourceLabel: "Component Library", importPath: "@tgv/module-component-library/components/icons/SessionsIcon", Comp: I90 },
  { key: "library/IconSettings", name: "IconSettings", source: "library", sourceLabel: "Component Library", importPath: "@tgv/module-component-library/components/icons/SettingsIcon", Comp: I91 },
  { key: "library/SignOutIcon", name: "SignOutIcon", source: "library", sourceLabel: "Component Library", importPath: "@tgv/module-component-library/components/icons/SignOutIcon", Comp: I92 },
  { key: "library/IconStorage", name: "IconStorage", source: "library", sourceLabel: "Component Library", importPath: "@tgv/module-component-library/components/icons/StorageIcon", Comp: I93 },
  { key: "library/IconStorefront", name: "IconStorefront", source: "library", sourceLabel: "Component Library", importPath: "@tgv/module-component-library/components/icons/StorefrontIcon", Comp: I94 },
  { key: "library/IconSubscription", name: "IconSubscription", source: "library", sourceLabel: "Component Library", importPath: "@tgv/module-component-library/components/icons/SubscriptionIcon", Comp: I95 },
  { key: "library/IconUser", name: "IconUser", source: "library", sourceLabel: "Component Library", importPath: "@tgv/module-component-library/components/icons/UserIcon", Comp: I96 },
  { key: "library/IconWallet", name: "IconWallet", source: "library", sourceLabel: "Component Library", importPath: "@tgv/module-component-library/components/icons/WalletIcon", Comp: I97 },
  { key: "library/FacebookIcon", name: "FacebookIcon", source: "library", sourceLabel: "Component Library", importPath: "@tgv/module-component-library/components/icons/facebook/FacebookIcon", Comp: I98 },
  { key: "tgv-v5/WebsiteBuilderIcon", name: "WebsiteBuilderIcon", source: "tgv-v5", sourceLabel: "TGV v5 Feature", importPath: "@tgv/module-component-library/components/tgv-v5", Comp: I99 },
  { key: "tgv-v5/BookingsIcon", name: "BookingsIcon", source: "tgv-v5", sourceLabel: "TGV v5 Feature", importPath: "@tgv/module-component-library/components/tgv-v5", Comp: I100 },
  { key: "tgv-v5/MeetingsIcon", name: "MeetingsIcon", source: "tgv-v5", sourceLabel: "TGV v5 Feature", importPath: "@tgv/module-component-library/components/tgv-v5", Comp: I101 },
  { key: "tgv-v5/PaymentsIcon", name: "PaymentsIcon", source: "tgv-v5", sourceLabel: "TGV v5 Feature", importPath: "@tgv/module-component-library/components/tgv-v5", Comp: I102 },
  { key: "tgv-v5/ClientDashboardIcon", name: "ClientDashboardIcon", source: "tgv-v5", sourceLabel: "TGV v5 Feature", importPath: "@tgv/module-component-library/components/tgv-v5", Comp: I103 },
  { key: "tgv-v5/CustomWebsitesIcon", name: "CustomWebsitesIcon", source: "tgv-v5", sourceLabel: "TGV v5 Feature", importPath: "@tgv/module-component-library/components/tgv-v5", Comp: I104 },
  { key: "video-stage/MagnifierIcon", name: "MagnifierIcon", source: "video-stage", sourceLabel: "Video Calls", importPath: "@tgv/module-video-calls/meetings/stage/icons", Comp: I105 },
  { key: "video-stage/WaitingRoomIcon", name: "WaitingRoomIcon", source: "video-stage", sourceLabel: "Video Calls", importPath: "@tgv/module-video-calls/meetings/stage/icons", Comp: I106 },
  { key: "video-stage/MoreIcon", name: "MoreIcon", source: "video-stage", sourceLabel: "Video Calls", importPath: "@tgv/module-video-calls/meetings/stage/icons", Comp: I107 },
  { key: "video-stage/PinIcon", name: "PinIcon", source: "video-stage", sourceLabel: "Video Calls", importPath: "@tgv/module-video-calls/meetings/stage/icons", Comp: I108 },
  { key: "video-stage/SwitchScreenIcon", name: "SwitchScreenIcon", source: "video-stage", sourceLabel: "Video Calls", importPath: "@tgv/module-video-calls/meetings/stage/icons", Comp: I109 },
  { key: "video-stage/SelfViewIcon", name: "SelfViewIcon", source: "video-stage", sourceLabel: "Video Calls", importPath: "@tgv/module-video-calls/meetings/stage/icons", Comp: I110 },
  { key: "video-stage/SpeakerViewIcon", name: "SpeakerViewIcon", source: "video-stage", sourceLabel: "Video Calls", importPath: "@tgv/module-video-calls/meetings/stage/icons", Comp: I111 },
  { key: "video-stage/GalleryViewIcon", name: "GalleryViewIcon", source: "video-stage", sourceLabel: "Video Calls", importPath: "@tgv/module-video-calls/meetings/stage/icons", Comp: I112 },
  { key: "video-stage/CloseIcon", name: "CloseIcon", source: "video-stage", sourceLabel: "Video Calls", importPath: "@tgv/module-video-calls/meetings/stage/icons", Comp: I113 },
  { key: "video-stage/ChevronIcon", name: "ChevronIcon", source: "video-stage", sourceLabel: "Video Calls", importPath: "@tgv/module-video-calls/meetings/stage/icons", Comp: I114 },
  { key: "video-stage/ChevronLeftIcon", name: "ChevronLeftIcon", source: "video-stage", sourceLabel: "Video Calls", importPath: "@tgv/module-video-calls/meetings/stage/icons", Comp: I115 },
  { key: "video-stage/ChevronRightIcon", name: "ChevronRightIcon", source: "video-stage", sourceLabel: "Video Calls", importPath: "@tgv/module-video-calls/meetings/stage/icons", Comp: I116 },
  { key: "video-stage/FullscreenIcon", name: "FullscreenIcon", source: "video-stage", sourceLabel: "Video Calls", importPath: "@tgv/module-video-calls/meetings/stage/icons", Comp: I117 },
  { key: "video-stage/ExitFullscreenIcon", name: "ExitFullscreenIcon", source: "video-stage", sourceLabel: "Video Calls", importPath: "@tgv/module-video-calls/meetings/stage/icons", Comp: I118 },
  { key: "video-stage/PopOutIcon", name: "PopOutIcon", source: "video-stage", sourceLabel: "Video Calls", importPath: "@tgv/module-video-calls/meetings/stage/icons", Comp: I119 },
  { key: "video-stage/RecordIcon", name: "RecordIcon", source: "video-stage", sourceLabel: "Video Calls", importPath: "@tgv/module-video-calls/meetings/stage/icons", Comp: I120 },
  { key: "video-stage/StopIcon", name: "StopIcon", source: "video-stage", sourceLabel: "Video Calls", importPath: "@tgv/module-video-calls/meetings/stage/icons", Comp: I121 },
  { key: "video-stage/LinkIcon", name: "LinkIcon", source: "video-stage", sourceLabel: "Video Calls", importPath: "@tgv/module-video-calls/meetings/stage/icons", Comp: I122 },
  { key: "video-stage/EndCallIcon", name: "EndCallIcon", source: "video-stage", sourceLabel: "Video Calls", importPath: "@tgv/module-video-calls/meetings/stage/icons", Comp: I123 },
  { key: "video-stage/LeaveIcon", name: "LeaveIcon", source: "video-stage", sourceLabel: "Video Calls", importPath: "@tgv/module-video-calls/meetings/stage/icons", Comp: I124 },
  { key: "video-stage/ChatIcon", name: "ChatIcon", source: "video-stage", sourceLabel: "Video Calls", importPath: "@tgv/module-video-calls/meetings/stage/icons", Comp: I125 },
  { key: "video-stage/PeopleIcon", name: "PeopleIcon", source: "video-stage", sourceLabel: "Video Calls", importPath: "@tgv/module-video-calls/meetings/stage/icons", Comp: I126 },
  { key: "video-stage/BreakoutIcon", name: "BreakoutIcon", source: "video-stage", sourceLabel: "Video Calls", importPath: "@tgv/module-video-calls/meetings/stage/icons", Comp: I127 },
  { key: "video-stage/TimerIcon", name: "TimerIcon", source: "video-stage", sourceLabel: "Video Calls", importPath: "@tgv/module-video-calls/meetings/stage/icons", Comp: I128 },
  { key: "video-stage/GearIcon", name: "GearIcon", source: "video-stage", sourceLabel: "Video Calls", importPath: "@tgv/module-video-calls/meetings/stage/icons", Comp: I129 },
  { key: "video-stage/SendIcon", name: "SendIcon", source: "video-stage", sourceLabel: "Video Calls", importPath: "@tgv/module-video-calls/meetings/stage/icons", Comp: I130 },
  { key: "video-leave/LeaveIcon", name: "LeaveIcon", source: "video-leave", sourceLabel: "Video Calls", importPath: "@tgv/module-video-calls/_icons/LeaveIcon", Comp: I131 },
  { key: "editor-toolbar/IconDesktop", name: "IconDesktop", source: "editor-toolbar", sourceLabel: "Page Editor toolbar", importPath: "@tgv/module-page-editor/editor/page-editor/toolbar/EditorToolbar.icons", Comp: I132 },
  { key: "editor-toolbar/IconMobile", name: "IconMobile", source: "editor-toolbar", sourceLabel: "Page Editor toolbar", importPath: "@tgv/module-page-editor/editor/page-editor/toolbar/EditorToolbar.icons", Comp: I133 },
  { key: "editor-toolbar/IconUndo", name: "IconUndo", source: "editor-toolbar", sourceLabel: "Page Editor toolbar", importPath: "@tgv/module-page-editor/editor/page-editor/toolbar/EditorToolbar.icons", Comp: I134 },
  { key: "editor-toolbar/IconRedo", name: "IconRedo", source: "editor-toolbar", sourceLabel: "Page Editor toolbar", importPath: "@tgv/module-page-editor/editor/page-editor/toolbar/EditorToolbar.icons", Comp: I135 },
  { key: "editor-toolbar/IconDots", name: "IconDots", source: "editor-toolbar", sourceLabel: "Page Editor toolbar", importPath: "@tgv/module-page-editor/editor/page-editor/toolbar/EditorToolbar.icons", Comp: I136 },
  { key: "editor-toolbar/IconEye", name: "IconEye", source: "editor-toolbar", sourceLabel: "Page Editor toolbar", importPath: "@tgv/module-page-editor/editor/page-editor/toolbar/EditorToolbar.icons", Comp: I137 },
  { key: "editor-toolbar/IconKeyboard", name: "IconKeyboard", source: "editor-toolbar", sourceLabel: "Page Editor toolbar", importPath: "@tgv/module-page-editor/editor/page-editor/toolbar/EditorToolbar.icons", Comp: I138 },
  { key: "editor-toolbar/IconSupport", name: "IconSupport", source: "editor-toolbar", sourceLabel: "Page Editor toolbar", importPath: "@tgv/module-page-editor/editor/page-editor/toolbar/EditorToolbar.icons", Comp: I139 },
  { key: "editor-toolbar/IconReset", name: "IconReset", source: "editor-toolbar", sourceLabel: "Page Editor toolbar", importPath: "@tgv/module-page-editor/editor/page-editor/toolbar/EditorToolbar.icons", Comp: I140 },
  { key: "editor-toolbar/IconResetToPublished", name: "IconResetToPublished", source: "editor-toolbar", sourceLabel: "Page Editor toolbar", importPath: "@tgv/module-page-editor/editor/page-editor/toolbar/EditorToolbar.icons", Comp: I141 },
  { key: "editor-toolbar/IconFullScreen", name: "IconFullScreen", source: "editor-toolbar", sourceLabel: "Page Editor toolbar", importPath: "@tgv/module-page-editor/editor/page-editor/toolbar/EditorToolbar.icons", Comp: I142 },
  { key: "editor-toolbar/IconNoEntry", name: "IconNoEntry", source: "editor-toolbar", sourceLabel: "Page Editor toolbar", importPath: "@tgv/module-page-editor/editor/page-editor/toolbar/EditorToolbar.icons", Comp: I143 },
  { key: "editor-toolbar/IconTrash", name: "IconTrash", source: "editor-toolbar", sourceLabel: "Page Editor toolbar", importPath: "@tgv/module-page-editor/editor/page-editor/toolbar/EditorToolbar.icons", Comp: I144 },
  { key: "editor-toolbar/IconEyeOff", name: "IconEyeOff", source: "editor-toolbar", sourceLabel: "Page Editor toolbar", importPath: "@tgv/module-page-editor/editor/page-editor/toolbar/EditorToolbar.icons", Comp: I145 },
  { key: "paint/IconReset", name: "IconReset", source: "paint", sourceLabel: "Paint Mode", importPath: "@tgv/module-page-editor/editor/paint/icons", Comp: I146 },
  { key: "paint/IconCopy", name: "IconCopy", source: "paint", sourceLabel: "Paint Mode", importPath: "@tgv/module-page-editor/editor/paint/icons", Comp: I147 },
  { key: "paint/IconPaste", name: "IconPaste", source: "paint", sourceLabel: "Paint Mode", importPath: "@tgv/module-page-editor/editor/paint/icons", Comp: I148 },
  { key: "paint/IconPlus", name: "IconPlus", source: "paint", sourceLabel: "Paint Mode", importPath: "@tgv/module-page-editor/editor/paint/icons", Comp: I149 },
  { key: "paint/IconTrash", name: "IconTrash", source: "paint", sourceLabel: "Paint Mode", importPath: "@tgv/module-page-editor/editor/paint/icons", Comp: I150 },
  { key: "paint/IconEye", name: "IconEye", source: "paint", sourceLabel: "Paint Mode", importPath: "@tgv/module-page-editor/editor/paint/icons", Comp: I151 },
  { key: "paint/IconEyeOff", name: "IconEyeOff", source: "paint", sourceLabel: "Paint Mode", importPath: "@tgv/module-page-editor/editor/paint/icons", Comp: I152 },
  { key: "paint/IconLock", name: "IconLock", source: "paint", sourceLabel: "Paint Mode", importPath: "@tgv/module-page-editor/editor/paint/icons", Comp: I153 },
  { key: "paint/IconUnlock", name: "IconUnlock", source: "paint", sourceLabel: "Paint Mode", importPath: "@tgv/module-page-editor/editor/paint/icons", Comp: I154 },
  { key: "link-tools/LinkIcon", name: "LinkIcon", source: "link-tools", sourceLabel: "Link Tools", importPath: "@tgv/module-page-editor/editor/component-library/marketing/link-tools/shared/icons", Comp: I155 },
  { key: "link-tools/QRIcon", name: "QRIcon", source: "link-tools", sourceLabel: "Link Tools", importPath: "@tgv/module-page-editor/editor/component-library/marketing/link-tools/shared/icons", Comp: I156 },
  { key: "link-tools/CopyIcon", name: "CopyIcon", source: "link-tools", sourceLabel: "Link Tools", importPath: "@tgv/module-page-editor/editor/component-library/marketing/link-tools/shared/icons", Comp: I157 },
  { key: "link-tools/TrashIcon", name: "TrashIcon", source: "link-tools", sourceLabel: "Link Tools", importPath: "@tgv/module-page-editor/editor/component-library/marketing/link-tools/shared/icons", Comp: I158 },
  { key: "link-tools/EditIcon", name: "EditIcon", source: "link-tools", sourceLabel: "Link Tools", importPath: "@tgv/module-page-editor/editor/component-library/marketing/link-tools/shared/icons", Comp: I159 },
  { key: "link-tools/CloseIcon", name: "CloseIcon", source: "link-tools", sourceLabel: "Link Tools", importPath: "@tgv/module-page-editor/editor/component-library/marketing/link-tools/shared/icons", Comp: I160 },
  { key: "link-tools/DownloadIcon", name: "DownloadIcon", source: "link-tools", sourceLabel: "Link Tools", importPath: "@tgv/module-page-editor/editor/component-library/marketing/link-tools/shared/icons", Comp: I161 },
];

export const SVG_SOURCE_GROUPS: { id: string; label: string; count: number }[] = [
  {
    "id": "office",
    "label": "Office icons",
    "count": 65
  },
  {
    "id": "office-brand",
    "label": "Office brand",
    "count": 3
  },
  {
    "id": "library",
    "label": "Component Library",
    "count": 31
  },
  {
    "id": "tgv-v5",
    "label": "TGV v5 Feature",
    "count": 6
  },
  {
    "id": "video-stage",
    "label": "Video Calls",
    "count": 27
  },
  {
    "id": "editor-toolbar",
    "label": "Page Editor toolbar",
    "count": 14
  },
  {
    "id": "paint",
    "label": "Paint Mode",
    "count": 9
  },
  {
    "id": "link-tools",
    "label": "Link Tools",
    "count": 7
  }
];
