-- 01-theme.sql — GENERATED by sql/resonantweaver-migration/generate.mjs.
-- DO NOT HAND-EDIT: the next run overwrites it. Change her source, or copy.mjs,
-- and re-run. `--check` fails if this file is stale, so a drifting edit is
-- caught rather than merged.
--
-- Her identity as three site-scoped rows: the palette and type (`theme`),
-- the two ambient orbs and the ground they drift over (`siteBackground`), and
-- the Cormorant Garamond faces that make the type real (`siteFonts`).
--
-- WHY THE FONT ROW EXISTS AT ALL. A theme has always been able to NAME a family;
-- nothing loaded one. On her own app the face arrived through a stylesheet
-- `@import` that does not travel with her pages — so without this row her site
-- would come up in Georgia with every colour, size and word correct.
--
-- The muted text and the surface are FLATTENED alphas: `rgba(BONE, .65)` and
-- `rgba(4, 20, 19, .9)` over her ground. The colour roles are hex-only by
-- design, and the flattened value is what a browser paints for those pixels.
--
--   psql -v ON_ERROR_STOP=1 -d tgv_db -f sql/resonantweaver-migration/01-theme.sql

\set ON_ERROR_STOP on

BEGIN;

SELECT set_config('app.actor', 'migration:resonantweaver-01-theme', true);

-- ── theme ────────────────────────────────────────────────────────────────
INSERT INTO public.content_overrides (key, lang, mode, user_id, data, updated_at, site)
SELECT 'theme', 'en', 'published', NULL, $rwjson${
  "colors": {
    "background": "#061814",
    "surface": "#041413",
    "text": "#e8e5da",
    "textMuted": "#999d95",
    "accent1": "#48d2b9",
    "accent2": "#b78a77",
    "accent3": "#b78a77"
  },
  "fonts": {
    "heading": "Cormorant Garamond, Georgia, serif",
    "body": "Cormorant Garamond, Georgia, serif"
  },
  "radius": {
    "card": "14px",
    "button": "8px",
    "small": "4px"
  }
}$rwjson$::jsonb, now(), 'resonantweaver'
 WHERE NOT EXISTS (
   SELECT 1 FROM public.content_overrides
    WHERE site = 'resonantweaver' AND key = 'theme'
      AND lang = 'en' AND mode = 'published'
      AND user_id IS NOT DISTINCT FROM NULL
 );

-- ── siteBackground ────────────────────────────────────────────────────────────────
INSERT INTO public.content_overrides (key, lang, mode, user_id, data, updated_at, site)
SELECT 'siteBackground', 'en', 'published', NULL, $rwjson${
  "orbs": [
    {
      "color": "#b78a77",
      "top": -20,
      "left": -20,
      "size": 80,
      "blur": 90,
      "alpha": 0.07,
      "from": 0.5,
      "to": 0.85,
      "driftX": 10,
      "driftY": 10,
      "duration": 22
    },
    {
      "color": "#48d2b9",
      "bottom": -20,
      "right": -20,
      "size": 80,
      "blur": 90,
      "alpha": 0.06,
      "from": 0.35,
      "to": 0.65,
      "driftX": -10,
      "driftY": -6,
      "duration": 28
    }
  ],
  "color": "#061814"
}$rwjson$::jsonb, now(), 'resonantweaver'
 WHERE NOT EXISTS (
   SELECT 1 FROM public.content_overrides
    WHERE site = 'resonantweaver' AND key = 'siteBackground'
      AND lang = 'en' AND mode = 'published'
      AND user_id IS NOT DISTINCT FROM NULL
 );

-- ── siteFonts ────────────────────────────────────────────────────────────────
INSERT INTO public.content_overrides (key, lang, mode, user_id, data, updated_at, site)
SELECT 'siteFonts', 'en', 'published', NULL, $rwjson${
  "faces": [
    {
      "family": "Cormorant Garamond",
      "src": "/fonts/tenants/resonantweaver/cormorant-garamond-latin.woff2",
      "weight": "300 700",
      "style": "normal",
      "display": "swap"
    },
    {
      "family": "Cormorant Garamond",
      "src": "/fonts/tenants/resonantweaver/cormorant-garamond-latin-italic.woff2",
      "weight": "300 700",
      "style": "italic",
      "display": "swap"
    }
  ]
}$rwjson$::jsonb, now(), 'resonantweaver'
 WHERE NOT EXISTS (
   SELECT 1 FROM public.content_overrides
    WHERE site = 'resonantweaver' AND key = 'siteFonts'
      AND lang = 'en' AND mode = 'published'
      AND user_id IS NOT DISTINCT FROM NULL
 );

-- ── assertions ─────────────────────────────────────────────────────────────
DO $$
DECLARE n int;
BEGIN
  SELECT count(*) INTO n FROM public.content_overrides
   WHERE site = 'resonantweaver' AND mode = 'published' AND user_id IS NULL
     AND key IN ('theme', 'siteBackground', 'siteFonts');
  IF n <> 3 THEN
    RAISE EXCEPTION 'assert: expected 3 identity rows, found %', n;
  END IF;

  -- A face that points at a path HQ does not serve loads nothing and falls back
  -- in silence — the exact failure this row exists to prevent.
  SELECT count(*) INTO n FROM public.content_overrides c,
       LATERAL jsonb_array_elements(c.data->'faces') f
   WHERE c.site = 'resonantweaver' AND c.key = 'siteFonts'
     AND f->>'src' NOT LIKE '/fonts/tenants/resonantweaver/%';
  IF n <> 0 THEN
    RAISE EXCEPTION 'assert: % font face(s) point outside the tenant font dir', n;
  END IF;

  -- The theme names a family; siteFonts must actually carry it.
  SELECT count(*) INTO n FROM public.content_overrides t
   WHERE t.site = 'resonantweaver' AND t.key = 'theme'
     AND NOT EXISTS (
       SELECT 1 FROM public.content_overrides c,
            LATERAL jsonb_array_elements(c.data->'faces') f
        WHERE c.site = t.site AND c.key = 'siteFonts'
          AND t.data->'fonts'->>'body' LIKE '%' || (f->>'family') || '%'
     );
  IF n <> 0 THEN
    RAISE EXCEPTION 'assert: the theme names a font no face loads';
  END IF;

  RAISE NOTICE 'assertions passed';
END $$;

SELECT key, jsonb_pretty(data) FROM public.content_overrides
 WHERE site = 'resonantweaver' AND mode = 'published' AND user_id IS NULL
 ORDER BY key;

COMMIT;
