-- 01-theme.sql — GENERATED by sql/resonantweaver-migration/generate.mjs.
-- DO NOT HAND-EDIT: the next run overwrites it. Change her source, or copy.mjs,
-- and re-run. `--check` fails if this file is stale, so a drifting edit is
-- caught rather than merged.
--
-- Her identity as three site-scoped rows: the palette and type (`theme`),
-- the sky behind every page (`siteBackground`), and the faces that make the
-- type real (`siteFonts`).
--
-- WHOSE LOOK THIS IS. The star landing's, not OnePage's — Gio's ruling of
-- 2026-08-06, after the parity pass showed a site that had changed colour and
-- typeface. Phase 1 read the ground and the type off `OnePage.styles.ts` and
-- `tokens.ts`; both are genuinely hers, but they belong to the one-pager she
-- retired, and the pooled home IS the star landing. That page declares
-- `#06111c` and Science Gothic over Space Grotesk; `SERIF` (Cormorant) appears
-- there only under `&[data-font-preview="original"]`, the alternative she was
-- previewing through her own FontPreviewSwitch. Her live home and /starseed/
-- wear the gothic; only /journey/ wears the serif, and one theme row cannot
-- name both.
--
-- WHY THE FONT ROW EXISTS AT ALL. A theme has always been able to NAME a family;
-- nothing loaded one. On her own app the faces arrive through `next/font` and a
-- stylesheet `@import`, neither of which travels with her pages — so without
-- this row her site would come up in a system sans with every colour, size and
-- word correct.
--
-- SIX ROLES SINCE 2026-08-07, and Cormorant is no longer among the unnamed.
-- The theme could hold `heading` and `body`; her DOM carries five families,
-- so the pooled render collapsed four of them into one and 145 elements on the
-- home page alone wore the wrong face — invisible to a colour check, invisible
-- to a word check, and the largest single delta the parity harness measured.
-- `display`, `serif`, `mono` and `accent` are the other four levers; every
-- one of them is asserted below against a face that actually loads, because a
-- role naming a family nothing serves is a role that silently means Arial.
--
-- The muted text and the surface are FLATTENED alphas: `rgba(BONE, .65)` and
-- `rgba(4, 20, 19, .9)` over her ground. The colour roles are hex-only by
-- design, and the flattened value is what a browser paints for those pixels.
--
-- RE-RUNNABLE, AND IT UPDATES. The first version only inserted where nothing
-- existed, which made a correction impossible to apply — the rows were already
-- there, so a re-run was a silent no-op and the wrong identity stayed live.
-- It now writes the migrated identity whether or not a row exists. That means
-- re-running it DISCARDS studio edits to these three keys; the plan-17 capture
-- trigger records every change to `content_overrides`, so a clobber is visible
-- in Client Versions and revertible, but do not re-run this after Marthe starts
-- editing her theme.
--
--   psql -v ON_ERROR_STOP=1 -d tgv_db -f sql/resonantweaver-migration/01-theme.sql

\set ON_ERROR_STOP on

BEGIN;

SELECT set_config('app.actor', 'migration:resonantweaver-01-theme', true);

-- ── theme ────────────────────────────────────────────────────────────────
INSERT INTO public.content_overrides (key, lang, mode, user_id, data, updated_at, site)
SELECT 'theme', 'en', 'published', NULL, $rwjson${
  "colors": {
    "background": "#06111c",
    "surface": "#041414",
    "text": "#e8e5da",
    "textMuted": "#999b98",
    "accent1": "#48d2b9",
    "accent2": "#b78a77",
    "accent3": "#b78a77"
  },
  "fonts": {
    "display": "Science Gothic, Space Grotesk, sans-serif",
    "heading": "Science Gothic, Space Grotesk, sans-serif",
    "body": "Space Grotesk, ui-sans-serif, system-ui, sans-serif",
    "serif": "Cormorant Garamond, Georgia, serif",
    "mono": "Ubuntu Mono, ui-monospace, SFMono-Regular, Menlo, monospace",
    "accent": "Space Mono, Ubuntu Mono, ui-monospace, monospace"
  },
  "radius": {
    "card": "14px",
    "button": "8px",
    "small": "4px"
  }
}$rwjson$::jsonb, now(), 'resonantweaver'
 WHERE NOT EXISTS (
   SELECT 1 FROM public.content_overrides
    WHERE site = 'resonantweaver' AND key = 'theme'
      AND lang = 'en' AND mode = 'published'
      AND user_id IS NOT DISTINCT FROM NULL
 );

UPDATE public.content_overrides
   SET data = $rwjson${
  "colors": {
    "background": "#06111c",
    "surface": "#041414",
    "text": "#e8e5da",
    "textMuted": "#999b98",
    "accent1": "#48d2b9",
    "accent2": "#b78a77",
    "accent3": "#b78a77"
  },
  "fonts": {
    "display": "Science Gothic, Space Grotesk, sans-serif",
    "heading": "Science Gothic, Space Grotesk, sans-serif",
    "body": "Space Grotesk, ui-sans-serif, system-ui, sans-serif",
    "serif": "Cormorant Garamond, Georgia, serif",
    "mono": "Ubuntu Mono, ui-monospace, SFMono-Regular, Menlo, monospace",
    "accent": "Space Mono, Ubuntu Mono, ui-monospace, monospace"
  },
  "radius": {
    "card": "14px",
    "button": "8px",
    "small": "4px"
  }
}$rwjson$::jsonb, updated_at = now()
 WHERE site = 'resonantweaver' AND key = 'theme'
   AND lang = 'en' AND mode = 'published'
   AND user_id IS NOT DISTINCT FROM NULL
   AND data IS DISTINCT FROM $rwjson${
  "colors": {
    "background": "#06111c",
    "surface": "#041414",
    "text": "#e8e5da",
    "textMuted": "#999b98",
    "accent1": "#48d2b9",
    "accent2": "#b78a77",
    "accent3": "#b78a77"
  },
  "fonts": {
    "display": "Science Gothic, Space Grotesk, sans-serif",
    "heading": "Science Gothic, Space Grotesk, sans-serif",
    "body": "Space Grotesk, ui-sans-serif, system-ui, sans-serif",
    "serif": "Cormorant Garamond, Georgia, serif",
    "mono": "Ubuntu Mono, ui-monospace, SFMono-Regular, Menlo, monospace",
    "accent": "Space Mono, Ubuntu Mono, ui-monospace, monospace"
  },
  "radius": {
    "card": "14px",
    "button": "8px",
    "small": "4px"
  }
}$rwjson$::jsonb;

-- ── siteBackground ────────────────────────────────────────────────────────────────
INSERT INTO public.content_overrides (key, lang, mode, user_id, data, updated_at, site)
SELECT 'siteBackground', 'en', 'published', NULL, $rwjson${
  "orbs": [
    {
      "color": "#235279",
      "top": -6,
      "left": 17,
      "width": 66,
      "height": 36,
      "size": 66,
      "blur": 0,
      "alpha": 0.2,
      "from": 1,
      "to": 1,
      "duration": 0
    },
    {
      "color": "#48d2b9",
      "bottom": 3,
      "right": -7,
      "width": 50,
      "height": 34,
      "size": 50,
      "blur": 0,
      "alpha": 0.035,
      "from": 1,
      "to": 1,
      "duration": 0
    }
  ],
  "color": "#06111c",
  "scrollbarGutter": true
}$rwjson$::jsonb, now(), 'resonantweaver'
 WHERE NOT EXISTS (
   SELECT 1 FROM public.content_overrides
    WHERE site = 'resonantweaver' AND key = 'siteBackground'
      AND lang = 'en' AND mode = 'published'
      AND user_id IS NOT DISTINCT FROM NULL
 );

UPDATE public.content_overrides
   SET data = $rwjson${
  "orbs": [
    {
      "color": "#235279",
      "top": -6,
      "left": 17,
      "width": 66,
      "height": 36,
      "size": 66,
      "blur": 0,
      "alpha": 0.2,
      "from": 1,
      "to": 1,
      "duration": 0
    },
    {
      "color": "#48d2b9",
      "bottom": 3,
      "right": -7,
      "width": 50,
      "height": 34,
      "size": 50,
      "blur": 0,
      "alpha": 0.035,
      "from": 1,
      "to": 1,
      "duration": 0
    }
  ],
  "color": "#06111c",
  "scrollbarGutter": true
}$rwjson$::jsonb, updated_at = now()
 WHERE site = 'resonantweaver' AND key = 'siteBackground'
   AND lang = 'en' AND mode = 'published'
   AND user_id IS NOT DISTINCT FROM NULL
   AND data IS DISTINCT FROM $rwjson${
  "orbs": [
    {
      "color": "#235279",
      "top": -6,
      "left": 17,
      "width": 66,
      "height": 36,
      "size": 66,
      "blur": 0,
      "alpha": 0.2,
      "from": 1,
      "to": 1,
      "duration": 0
    },
    {
      "color": "#48d2b9",
      "bottom": 3,
      "right": -7,
      "width": 50,
      "height": 34,
      "size": 50,
      "blur": 0,
      "alpha": 0.035,
      "from": 1,
      "to": 1,
      "duration": 0
    }
  ],
  "color": "#06111c",
  "scrollbarGutter": true
}$rwjson$::jsonb;

-- ── siteFonts ────────────────────────────────────────────────────────────────
INSERT INTO public.content_overrides (key, lang, mode, user_id, data, updated_at, site)
SELECT 'siteFonts', 'en', 'published', NULL, $rwjson${
  "faces": [
    {
      "family": "Science Gothic",
      "src": "/fonts/tenants/resonantweaver/science-gothic-variable.woff2",
      "weight": "400 800",
      "style": "normal",
      "display": "swap"
    },
    {
      "family": "Space Grotesk",
      "src": "/fonts/tenants/resonantweaver/space-grotesk-latin.woff2",
      "weight": "300 700",
      "style": "normal",
      "display": "swap"
    },
    {
      "family": "Cormorant Garamond",
      "src": "/fonts/tenants/resonantweaver/cormorant-garamond-latin.woff2",
      "weight": "300 700",
      "style": "normal",
      "display": "swap"
    },
    {
      "family": "Cormorant Garamond",
      "src": "/fonts/tenants/resonantweaver/cormorant-garamond-latin-italic.woff2",
      "weight": "300 700",
      "style": "italic",
      "display": "swap"
    },
    {
      "family": "Space Mono",
      "src": "/fonts/tenants/resonantweaver/space-mono-latin.woff2",
      "weight": "400",
      "style": "normal",
      "display": "swap",
      "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
    },
    {
      "family": "Space Mono",
      "src": "/fonts/tenants/resonantweaver/space-mono-latin-bold.woff2",
      "weight": "700",
      "style": "normal",
      "display": "swap",
      "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
    },
    {
      "family": "Ubuntu Mono",
      "src": "/fonts/tenants/resonantweaver/ubuntu-mono-latin.woff2",
      "weight": "400",
      "style": "normal",
      "display": "swap",
      "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
    },
    {
      "family": "Ubuntu Mono",
      "src": "/fonts/tenants/resonantweaver/ubuntu-mono-greek.woff2",
      "weight": "400",
      "style": "normal",
      "display": "swap",
      "unicodeRange": "U+0370-0377,U+037A-037F,U+0384-038A,U+038C,U+038E-03A1,U+03A3-03FF"
    }
  ]
}$rwjson$::jsonb, now(), 'resonantweaver'
 WHERE NOT EXISTS (
   SELECT 1 FROM public.content_overrides
    WHERE site = 'resonantweaver' AND key = 'siteFonts'
      AND lang = 'en' AND mode = 'published'
      AND user_id IS NOT DISTINCT FROM NULL
 );

UPDATE public.content_overrides
   SET data = $rwjson${
  "faces": [
    {
      "family": "Science Gothic",
      "src": "/fonts/tenants/resonantweaver/science-gothic-variable.woff2",
      "weight": "400 800",
      "style": "normal",
      "display": "swap"
    },
    {
      "family": "Space Grotesk",
      "src": "/fonts/tenants/resonantweaver/space-grotesk-latin.woff2",
      "weight": "300 700",
      "style": "normal",
      "display": "swap"
    },
    {
      "family": "Cormorant Garamond",
      "src": "/fonts/tenants/resonantweaver/cormorant-garamond-latin.woff2",
      "weight": "300 700",
      "style": "normal",
      "display": "swap"
    },
    {
      "family": "Cormorant Garamond",
      "src": "/fonts/tenants/resonantweaver/cormorant-garamond-latin-italic.woff2",
      "weight": "300 700",
      "style": "italic",
      "display": "swap"
    },
    {
      "family": "Space Mono",
      "src": "/fonts/tenants/resonantweaver/space-mono-latin.woff2",
      "weight": "400",
      "style": "normal",
      "display": "swap",
      "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
    },
    {
      "family": "Space Mono",
      "src": "/fonts/tenants/resonantweaver/space-mono-latin-bold.woff2",
      "weight": "700",
      "style": "normal",
      "display": "swap",
      "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
    },
    {
      "family": "Ubuntu Mono",
      "src": "/fonts/tenants/resonantweaver/ubuntu-mono-latin.woff2",
      "weight": "400",
      "style": "normal",
      "display": "swap",
      "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
    },
    {
      "family": "Ubuntu Mono",
      "src": "/fonts/tenants/resonantweaver/ubuntu-mono-greek.woff2",
      "weight": "400",
      "style": "normal",
      "display": "swap",
      "unicodeRange": "U+0370-0377,U+037A-037F,U+0384-038A,U+038C,U+038E-03A1,U+03A3-03FF"
    }
  ]
}$rwjson$::jsonb, updated_at = now()
 WHERE site = 'resonantweaver' AND key = 'siteFonts'
   AND lang = 'en' AND mode = 'published'
   AND user_id IS NOT DISTINCT FROM NULL
   AND data IS DISTINCT FROM $rwjson${
  "faces": [
    {
      "family": "Science Gothic",
      "src": "/fonts/tenants/resonantweaver/science-gothic-variable.woff2",
      "weight": "400 800",
      "style": "normal",
      "display": "swap"
    },
    {
      "family": "Space Grotesk",
      "src": "/fonts/tenants/resonantweaver/space-grotesk-latin.woff2",
      "weight": "300 700",
      "style": "normal",
      "display": "swap"
    },
    {
      "family": "Cormorant Garamond",
      "src": "/fonts/tenants/resonantweaver/cormorant-garamond-latin.woff2",
      "weight": "300 700",
      "style": "normal",
      "display": "swap"
    },
    {
      "family": "Cormorant Garamond",
      "src": "/fonts/tenants/resonantweaver/cormorant-garamond-latin-italic.woff2",
      "weight": "300 700",
      "style": "italic",
      "display": "swap"
    },
    {
      "family": "Space Mono",
      "src": "/fonts/tenants/resonantweaver/space-mono-latin.woff2",
      "weight": "400",
      "style": "normal",
      "display": "swap",
      "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
    },
    {
      "family": "Space Mono",
      "src": "/fonts/tenants/resonantweaver/space-mono-latin-bold.woff2",
      "weight": "700",
      "style": "normal",
      "display": "swap",
      "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
    },
    {
      "family": "Ubuntu Mono",
      "src": "/fonts/tenants/resonantweaver/ubuntu-mono-latin.woff2",
      "weight": "400",
      "style": "normal",
      "display": "swap",
      "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
    },
    {
      "family": "Ubuntu Mono",
      "src": "/fonts/tenants/resonantweaver/ubuntu-mono-greek.woff2",
      "weight": "400",
      "style": "normal",
      "display": "swap",
      "unicodeRange": "U+0370-0377,U+037A-037F,U+0384-038A,U+038C,U+038E-03A1,U+03A3-03FF"
    }
  ]
}$rwjson$::jsonb;

-- ── assertions ─────────────────────────────────────────────────────────────
DO $$
DECLARE n int; role text;
BEGIN
  SELECT count(*) INTO n FROM public.content_overrides
   WHERE site = 'resonantweaver' AND mode = 'published' AND user_id IS NULL
     AND key IN ('theme', 'siteBackground', 'siteFonts');
  IF n <> 3 THEN
    RAISE EXCEPTION 'assert: expected 3 identity rows, found %', n;
  END IF;

  -- A face that points at a path HQ does not serve loads nothing and falls back
  -- in silence — the exact failure this row exists to prevent.
  SELECT count(*) INTO n FROM public.content_overrides c,
       LATERAL jsonb_array_elements(c.data->'faces') f
   WHERE c.site = 'resonantweaver' AND c.key = 'siteFonts'
     AND f->>'src' NOT LIKE '/fonts/tenants/resonantweaver/%';
  IF n <> 0 THEN
    RAISE EXCEPTION 'assert: % font face(s) point outside the tenant font dir', n;
  END IF;

  -- The theme names families; siteFonts must actually carry them. EVERY role
  -- she declares, not a sample: each one here is a different family, and
  -- checking a subset is how the unchecked one falls back to a system sans in
  -- silence — correct colours, correct words, wrong site. The list is generated
  -- from the same `themeFonts` the row above is built from, so a role added
  -- there cannot arrive unasserted.
  FOR role IN SELECT unnest(ARRAY['display', 'heading', 'body', 'serif', 'mono', 'accent']) LOOP
    SELECT count(*) INTO n FROM public.content_overrides t
     WHERE t.site = 'resonantweaver' AND t.key = 'theme'
       AND NOT EXISTS (
         SELECT 1 FROM public.content_overrides c,
              LATERAL jsonb_array_elements(c.data->'faces') f
          WHERE c.site = t.site AND c.key = 'siteFonts'
            AND split_part(t.data->'fonts'->>role, ',', 1) = (f->>'family')
       );
    IF n <> 0 THEN
      RAISE EXCEPTION 'assert: the theme''s % font is a family no face loads', role;
    END IF;
  END LOOP;

  -- The sky is the star landing's, not the retired one-pager's. A wrong ground
  -- here is the difference between a blue night and a green one, and it is the
  -- defect the 2026-08-06 parity pass found.
  SELECT count(*) INTO n FROM public.content_overrides
   WHERE site = 'resonantweaver' AND key = 'siteBackground'
     AND data->>'color' = '#06111c';
  IF n <> 1 THEN
    RAISE EXCEPTION 'assert: siteBackground.color is not %', '#06111c';
  END IF;

  -- The reserved scrollbar gutter. Silent when wrong: every page simply lays
  -- out 15px wider than it does on her app, and only a narrow viewport shows it.
  SELECT count(*) INTO n FROM public.content_overrides
   WHERE site = 'resonantweaver' AND key = 'siteBackground'
     AND data->>'scrollbarGutter' = 'true';
  IF n <> 1 THEN
    RAISE EXCEPTION 'assert: siteBackground.scrollbarGutter is not reserved';
  END IF;

  RAISE NOTICE 'assertions passed';
END $$;

SELECT key, jsonb_pretty(data) FROM public.content_overrides
 WHERE site = 'resonantweaver' AND mode = 'published' AND user_id IS NULL
 ORDER BY key;

COMMIT;
