-- 02-pages.sql — GENERATED by sql/resonantweaver-migration/generate.mjs.
-- DO NOT HAND-EDIT: the next run overwrites it. Change her source, or copy.mjs,
-- and re-run. `--check` fails if this file is stale, so a drifting edit is
-- caught rather than merged.
--
-- Bucket A — her marketing content as `page_models` rows: the one-pager
-- (hero, intro, journey gateway, the offerings stack with its testimonial
-- bands, the FAQ, the contact form and the about panel) and /writing.
--
-- Contact form: 904a1f4d-26bb-42df-b3a2-a16a655fc99d (public.forms, owned by whoever owns her villager_sites row).
--
-- NOT AUTHORED HERE, and each for a stated reason:
--   • the journey (`/journey` and its blocks) and the starseed surfaces move
--     as PACKAGES in Phase 4 — canvas and scroll-driven motion is not catalog
--     material and re-authoring it would lose it. The gateway's words and its
--     link travel now; its seven chakra dots come with the package.
--   • the commerce funnel (`/pearl-chamber`, the landing-star tree) is bucket
--     B: app routes plus `SITE_SURFACES` grants, not rows. Until that lands,
--     the Pearl Chamber CTA below points at a path this renderer does not serve
--     yet — the same knowingly-broken link giocoelho's `/playlists` was, and
--     the same ruling: flip and port, don't hold the migration.
--
-- Every section leaves its colour roles EMPTY on purpose. They resolve through
-- `--tgv-*`, which 01-theme.sql rewrites to her palette — which is the whole
-- "strip the colours, backfill them as data" instruction: the same rows on an
-- unthemed site render in the platform's colours instead of hers.
--
--   psql -v ON_ERROR_STOP=1 -d tgv_db -f sql/resonantweaver-migration/02-pages.sql

\set ON_ERROR_STOP on

BEGIN;

SELECT set_config('app.actor', 'migration:resonantweaver-02-pages', true);

-- ── the contact form ───────────────────────────────────────────────────────
-- The section below is a `form-live`, which is reference-by-id: the definition
-- lives in `public.forms` and submissions land in her Forms inbox with the
-- anti-abuse engine in front of them. Porting ContactForm.tsx would have been a
-- second form doing the same job — the duplicate-but-different pair that starts
-- drift. Fields, labels, options and the thank-you line are generated from her
-- own dictionary, so the form a visitor meets is the one she wrote.
--
-- The id is DERIVED from the site and the slug, not random, so this file names
-- the same row every time it runs.
INSERT INTO public.forms (id, site_id, owner_member_id, slug, title, purpose, status, definition, definition_version)
SELECT '904a1f4d-26bb-42df-b3a2-a16a655fc99d'::uuid, v.id, o.member_id, 'contact', 'Get in touch',
       'general', 'published', $rwjson${
  "title": "Get in touch",
  "version": 1,
  "fields": [
    {
      "ref": "name",
      "type": "short_text",
      "title": "Name",
      "required": true
    },
    {
      "ref": "email",
      "type": "email",
      "title": "Email",
      "required": true
    },
    {
      "ref": "topic",
      "type": "dropdown",
      "title": "Topic",
      "required": true,
      "properties": {
        "options": [
          {
            "ref": "resonance-mirror",
            "label": "Resonance Mirror"
          },
          {
            "ref": "pulse-mirror",
            "label": "Pulse Mirror"
          },
          {
            "ref": "somatic-signature",
            "label": "Somatic Signature"
          },
          {
            "ref": "harmonic-sweep",
            "label": "Harmonic Sweep"
          },
          {
            "ref": "pearl-chamber",
            "label": "Pearl Chamber"
          }
        ],
        "allowOther": true,
        "otherPrompt": "Other"
      }
    },
    {
      "ref": "message",
      "type": "long_text",
      "title": "What would you like to create or explore?",
      "required": true
    }
  ],
  "settings": {
    "submitLabel": "Send Message"
  },
  "thankyou": {
    "title": "Thank you. I'll be in touch.",
    "description": ""
  }
}$rwjson$::jsonb, 1
  FROM public.villager_sites v
  JOIN LATERAL (
    SELECT member_id FROM public.villager WHERE site_id = v.id ORDER BY member_id LIMIT 1
  ) o ON true
 WHERE v.subdomain = 'resonantweaver'
   AND NOT EXISTS (SELECT 1 FROM public.forms WHERE id = '904a1f4d-26bb-42df-b3a2-a16a655fc99d'::uuid);

CREATE TEMP TABLE _rw_pages (slug text, title text, in_nav boolean, model jsonb)
  ON COMMIT DROP;

INSERT INTO _rw_pages VALUES ('home', 'Resonant Weaver', true, $rwjson${
  "id": "pm-rw-home",
  "slug": "home",
  "title": "Resonant Weaver",
  "chrome": {
    "navEnabled": true,
    "footerEnabled": true,
    "meta": {
      "description": "Remote energy readings and frequency anchoring delivered as a clear written PDF.",
      "keywords": [
        "Resonant Weaver",
        "remote energy reading",
        "energetic readings",
        "frequency anchor",
        "Resonance Mirror",
        "Pulse Mirror",
        "Somatic Signature",
        "Harmonic Sweep",
        "Pearl Chamber",
        "somatic guidance",
        "embodiment",
        "subtle energy",
        "Human Design"
      ],
      "ogImage": "/images/tenants/resonantweaver/RW-OG-logo.jpg"
    }
  },
  "sections": [
    {
      "id": "sec-hero",
      "type": "rf-split-hero",
      "label": "Hero",
      "blocks": [],
      "enabled": true,
      "config": {
        "props": {
          "markUrl": "/images/tenants/resonantweaver/Logo-RW-2026.svg",
          "markAlt": "",
          "markGlow": true,
          "markBreathe": true,
          "markRight": true,
          "eyebrow": "Galactic Bridge ✦ Energy Guide",
          "words": [
            "RESONANT",
            "WEAVER"
          ],
          "dropInitials": true,
          "ariaLabel": "Resonant Weaver",
          "tagline": "A return to yourself",
          "rule": true
        }
      }
    },
    {
      "id": "sec-star-intro",
      "type": "rf-media-copy",
      "label": "Intro",
      "blocks": [],
      "enabled": true,
      "config": {
        "props": {
          "imageUrl": "",
          "imageAlt": "",
          "imagePosition": "left",
          "eyebrow": "Where people begin",
          "eyebrowColor": "accent",
          "heading": "Knowing is a constant unfolding",
          "headingLevel": 2,
          "headingAccent": "",
          "paragraphs": [
            "Some people come here curious. Some are already sensing energy or receiving information they don't yet have language for. Some want to understand their own star pattern. Some want to develop the perception itself. Wherever you're starting from, there's a door in: begin with the stars, enter your own field, or train the perception that lets you meet the unseen directly."
          ],
          "chips": [],
          "ctas": []
        }
      }
    },
    {
      "id": "sec-star-doors",
      "type": "rf-door-card",
      "label": "Doors",
      "blocks": [],
      "enabled": true,
      "config": {
        "props": {
          "columns": 3,
          "heading": "",
          "ratio": "2 / 3",
          "ratioStacked": "1 / 1",
          "idleReveal": 0.62,
          "items": [
            {
              "index": "I · Door",
              "title": "Meet your galactic self",
              "copy": "Curious about your star currents or celestial pattern? Begin with the easiest possible first contact.",
              "cta": "Meet yourself",
              "href": "/starseed",
              "imageUrl": "/images/tenants/resonantweaver/GalacticSelf.jpg",
              "imageAlt": "A restrained constellation and astronomical observatory diagram emerging from darkness",
              "disabled": false,
              "disabledLabel": ""
            }
          ]
        }
      }
    },
    {
      "id": "sec-star-featured-intro",
      "type": "rf-media-copy",
      "label": "Featured — intro",
      "blocks": [],
      "enabled": true,
      "config": {
        "props": {
          "imageUrl": "",
          "imageAlt": "",
          "imagePosition": "left",
          "eyebrow": "Where to begin",
          "eyebrowColor": "accent",
          "heading": "Start here",
          "headingLevel": 2,
          "headingAccent": "",
          "paragraphs": [
            "The Starwoven Journey is the heart of this work right now. Around it sit a handful of readings and practices you can step into whenever you're ready."
          ],
          "chips": [],
          "ctas": []
        }
      }
    },
    {
      "id": "sec-star-featured",
      "type": "rf-offer-card",
      "label": "Featured",
      "blocks": [],
      "enabled": true,
      "config": {
        "props": {
          "columns": 3,
          "heading": "",
          "bulletGlyph": "✦",
          "padTop": 0,
          "padBottom": 25,
          "items": [
            {
              "anchorId": "starwoven-journey",
              "eyebrow": "01 · Your celestial pattern, read in full",
              "title": "Starwoven Journey",
              "sub": "",
              "body": "The full Starwoven Journey — a personalised, interactive exploration of your galactic themes, patterns and resonances.",
              "listLabel": "",
              "bullets": [],
              "note": "",
              "price": "$33",
              "ctaLabel": "Explore",
              "ctaHref": "/starseed/",
              "ctaTarget": "",
              "variant": "standard"
            },
            {
              "anchorId": "resonance-mirror",
              "eyebrow": "02 · The deep, full-spectrum reading",
              "title": "Resonance Mirror",
              "sub": "",
              "body": "Your energy field holds more information than most people ever get access to. This reading gives you that access.",
              "listLabel": "",
              "bullets": [],
              "note": "",
              "price": "$155",
              "ctaLabel": "Learn more",
              "ctaHref": "/landing-star-preview/offer/resonance-mirror/",
              "ctaTarget": "",
              "variant": "standard"
            },
            {
              "anchorId": "pearl-chamber",
              "eyebrow": "03 · A weekly holding for one intention",
              "title": "The Pearl Chamber",
              "sub": "",
              "body": "Your intention is placed inside the chamber and held there within 24 hours of purchase, where it is tended daily through meditation, energy work, and spoken enchantment.",
              "listLabel": "",
              "bullets": [],
              "note": "",
              "price": "$11",
              "ctaLabel": "Learn more",
              "ctaHref": "/landing-star-preview/offer/pearl-chamber/",
              "ctaTarget": "",
              "variant": "standard"
            }
          ]
        }
      }
    },
    {
      "id": "sec-star-fieldguide-intro",
      "type": "rf-media-copy",
      "label": "Field Guide — intro",
      "blocks": [],
      "enabled": true,
      "config": {
        "props": {
          "imageUrl": "",
          "imageAlt": "",
          "imagePosition": "left",
          "eyebrow": "An evolving archive",
          "eyebrowColor": "accent",
          "heading": "The Galactic Field Guide",
          "headingLevel": 2,
          "headingAccent": "",
          "paragraphs": [
            "A growing atlas of the fixed-star currents and the civilisations woven through them — 42 systems and counting. Some entries are complete with full plates; many are still being written or illustrated. Preview and founding access open before the full guide does."
          ],
          "chips": [],
          "ctas": []
        }
      }
    },
    {
      "id": "sec-star-fieldguide",
      "type": "rf-offer-card",
      "label": "Field Guide — tiles",
      "blocks": [],
      "enabled": true,
      "config": {
        "props": {
          "columns": 3,
          "heading": "",
          "bulletGlyph": "✦",
          "padTop": 0,
          "padBottom": 25,
          "items": [
            {
              "eyebrow": "01 · Civilisation",
              "title": "Lyra · Vega",
              "sub": "",
              "body": "",
              "listLabel": "",
              "bullets": [],
              "note": "",
              "price": "",
              "ctaLabel": "",
              "ctaHref": "",
              "variant": "standard"
            },
            {
              "eyebrow": "02 · Civilisation",
              "title": "Pleiades · Alcyone",
              "sub": "",
              "body": "",
              "listLabel": "",
              "bullets": [],
              "note": "",
              "price": "",
              "ctaLabel": "",
              "ctaHref": "",
              "variant": "standard"
            },
            {
              "eyebrow": "03 · Civilisation",
              "title": "Sirius · Canis Major",
              "sub": "",
              "body": "",
              "listLabel": "",
              "bullets": [],
              "note": "",
              "price": "",
              "ctaLabel": "",
              "ctaHref": "",
              "variant": "standard"
            }
          ]
        }
      }
    },
    {
      "id": "sec-star-fieldguide-notify",
      "type": "rf-media-copy",
      "label": "Field Guide — notify",
      "blocks": [],
      "enabled": true,
      "config": {
        "props": {
          "imageUrl": "",
          "imageAlt": "",
          "imagePosition": "left",
          "eyebrow": "",
          "eyebrowColor": "accent",
          "heading": "",
          "headingLevel": 2,
          "headingAccent": "",
          "paragraphs": [
            "The full guide isn't open yet. Get in touch to be notified once access is ready."
          ],
          "chips": [],
          "ctas": [
            {
              "label": "Ask about access",
              "href": "#contact",
              "variant": "ritual"
            }
          ]
        }
      }
    },
    {
      "id": "sec-star-faq",
      "type": "rf-accordion",
      "label": "FAQ",
      "blocks": [],
      "enabled": true,
      "config": {
        "props": {
          "heading": "Frequently Asked Questions",
          "lede": "Common queries about the nature of this work.",
          "defaultOpen": -1,
          "look": "panel",
          "centeredHead": true,
          "ruleUnderHead": true,
          "animate": true,
          "exclusive": true,
          "items": [
            {
              "name": "What is Resonant Weaver?",
              "body": "Resonant Weaver is my practice as an energy reader and guide. I work with the subtle field, the fixed stars of your birth sky, and the body. That takes shape as personal readings, one-to-one sessions, the interactive Starwoven Journey, and a growing Galactic Field Guide, so you can choose the doorway that fits where you are."
            },
            {
              "name": "What kind of guidance is this?",
              "body": "The offerings are reflective and interpretive in nature. They include perspectives, awareness, and optional suggestions related to personal experience, embodiment, or environment. Any adjustments or practices suggested, whether somatic or environmental, are invitations, not prescriptions. Resonant Weaver does not provide medical, psychological, or legal advice."
            },
            {
              "name": "What's your background?",
              "body": "I am certified in mediumship, Usui Reiki as a Master and Teacher, Quantum Astrology, and soul guide work, and I have spent years developing a way of reading energetic and stellar fields. I receive through clairsentience and claircognizance, then translate what I find into something grounded and usable."
            },
            {
              "name": "Is this mediumship or channeling?",
              "body": "This work draws on clairsentience and claircognizance as sensing tools. I translate what I receive into grounded reflections and practical suggestions, always aimed at coherence, capacity, and what your system can comfortably integrate now."
            },
            {
              "name": "Are readings remote?",
              "body": "Yes. Readings are completed remotely and shared as a written reflection by email. This allows the work to be done without scheduling or live interaction, and gives you space to receive it in your own time."
            },
            {
              "name": "What is the Starwoven Journey?",
              "body": "It is a personal reading of the fixed stars active in your birth sky, delivered as an interactive journey you move through at your own pace. It reveals your starseed lineages, your gifts and shadow gates, and the direction your life is asking to take. You only need your exact birth date, time and place to begin."
            },
            {
              "name": "Do I need to know astrology or Human Design?",
              "body": "No. You can come in with zero background. Anything drawn from Human Design or the stars is translated into plain language and grounded takeaways."
            },
            {
              "name": "Who is this for?",
              "body": "This work suits people who are curious about their subtle energy body, open to sensing and reflecting on subtle experience, and willing to take an active role in their own process. If you are looking for prediction, diagnosis, or an outside authority to decide for you, this may not be the right fit."
            },
            {
              "name": "How do I get started?",
              "body": "Choose the offering that calls to you and follow it, or write to me through the contact form below if you are not sure where to begin. For remote readings you do not need to prepare anything, and you will usually receive your written reflection by email within one to two business days."
            }
          ]
        }
      }
    },
    {
      "id": "sec-star-contact",
      "type": "form-live",
      "label": "Contact",
      "blocks": [],
      "enabled": true,
      "config": {
        "props": {
          "formId": "904a1f4d-26bb-42df-b3a2-a16a655fc99d",
          "accent": "",
          "hideHeader": false,
          "maxWidth": 640
        }
      }
    },
    {
      "id": "sec-star-about",
      "type": "rf-offer-card",
      "label": "About",
      "blocks": [],
      "enabled": true,
      "config": {
        "props": {
          "columns": 1,
          "heading": "",
          "bulletGlyph": "✦",
          "padTop": 0,
          "padBottom": 25,
          "items": [
            {
              "anchorId": "about",
              "eyebrow": "About Resonant Weaver",
              "title": "Between Earth and sky",
              "sub": "",
              "body": "I live in a small forest in Sweden, on a homestead we are slowly learning to run. Most things here have been figured out the hard way, from carrying water to making firewood to growing food from scratch. It has taught me to pay attention to what is actually there rather than what I expect to find.\n\nI have been drawn to what moves beneath the surface since I was a child. That curiosity became a practice, and the practice became this work. I am certified in mediumship, Usui Reiki as a Master and Teacher, Quantum Astrology, and soul guide work, and I have spent years developing a way of reading energetic and stellar fields that is closer to mapping than interpretation.\n\nI receive through clairsentience and claircognizance, feeling what is happening in a field directly, in my own system, then translating it into something grounded and usable. I also work with light language, spoken and through movement, when a field asks for direct tending rather than reflection.\n\nThe Starwoven Journey grew from all of this: reading the fixed stars of your birth sky as the lineages you carry, and helping them find a home in your human life.",
              "listLabel": "",
              "bullets": [],
              "note": "",
              "price": "",
              "ctaLabel": "",
              "ctaHref": "",
              "variant": "compact-media",
              "mediaUrl": "/images/tenants/resonantweaver/About-Portrait.png",
              "mediaAlt": "Portrait of Marthe",
              "mediaPortrait": true
            }
          ]
        }
      }
    }
  ]
}$rwjson$::jsonb);

INSERT INTO _rw_pages VALUES ('home-classic', 'Resonant Weaver — classic landing (archived)', false, $rwjson${
  "id": "pm-rw-home-classic",
  "slug": "home-classic",
  "title": "Resonant Weaver — classic landing (archived)",
  "chrome": {
    "navEnabled": true,
    "footerEnabled": true,
    "meta": {
      "description": "Remote energy readings and frequency anchoring delivered as a clear written PDF.",
      "keywords": [
        "Resonant Weaver",
        "remote energy reading",
        "energetic readings",
        "frequency anchor",
        "Resonance Mirror",
        "Pulse Mirror",
        "Somatic Signature",
        "Harmonic Sweep",
        "Pearl Chamber",
        "somatic guidance",
        "embodiment",
        "subtle energy",
        "Human Design"
      ],
      "ogImage": "/images/tenants/resonantweaver/RW-OG-logo.jpg",
      "noindex": true
    }
  },
  "sections": [
    {
      "id": "sec-hero",
      "type": "rf-split-hero",
      "label": "Hero",
      "blocks": [],
      "enabled": true,
      "config": {
        "props": {
          "markUrl": "/images/tenants/resonantweaver/Logo-RW-2026.svg",
          "markAlt": "",
          "markGlow": true,
          "markBreathe": true,
          "markRight": true,
          "eyebrow": "Galactic Bridge ✦ Energy Guide",
          "words": [
            "RESONANT",
            "WEAVER"
          ],
          "dropInitials": true,
          "ariaLabel": "Resonant Weaver",
          "tagline": "A return to yourself",
          "rule": true
        }
      }
    },
    {
      "id": "sec-intro",
      "type": "rf-media-copy",
      "label": "Intro",
      "blocks": [],
      "enabled": true,
      "config": {
        "props": {
          "imageUrl": "",
          "imageAlt": "",
          "imagePosition": "left",
          "eyebrow": "",
          "eyebrowColor": "accent",
          "heading": "",
          "headingLevel": 2,
          "headingAccent": "",
          "paragraphs": [
            "Most people have never truly felt themselves. Life moves fast, and the subtle layers of your own system are easy to lose track of. Through field readings and Human Design informed somatic practice, I help you get genuinely familiar with how your energy moves, what it carries, and what it feels like when it's actually yours.",
            "This work supports deeper awareness, wider perception, and the quiet internal coherence of knowing what is actually true for you."
          ],
          "chips": [],
          "ctas": []
        }
      }
    },
    {
      "id": "sec-journey-gateway",
      "type": "rf-media-copy",
      "label": "Journey gateway",
      "blocks": [],
      "enabled": true,
      "config": {
        "props": {
          "imageUrl": "",
          "imageAlt": "",
          "imagePosition": "left",
          "eyebrow": "Before you choose a service",
          "eyebrowColor": "amber",
          "heading": "",
          "headingLevel": 2,
          "headingAccent": "",
          "paragraphs": [
            "Where are you in your energetic field right now?",
            "A short self-guided journey through the seven energy centers"
          ],
          "chips": [],
          "ctas": [
            {
              "label": "Enter the field",
              "href": "/journey",
              "variant": "ritual"
            }
          ]
        }
      }
    },
    {
      "id": "sec-offer-1",
      "type": "rf-offer-card",
      "label": "Offerings 1",
      "blocks": [],
      "enabled": true,
      "config": {
        "props": {
          "columns": 1,
          "heading": "Work with me",
          "bulletGlyph": "✦",
          "padTop": 0,
          "padBottom": 25,
          "items": [
            {
              "anchorId": "resonance-mirror",
              "title": "Resonance Mirror",
              "sub": "The deep, full-spectrum reading",
              "body": "Your energy field holds more information than most people ever get access to. This reading gives you that access.\n\nThrough direct energetic perception, light language and pendulum work, I read what is present in your field right now. What is genuinely yours, what has been placed there, and what has been quietly distorting the signal. I work with what I find as I find it.\n\nWhat you receive is a personal field map, a detailed written reflection of everything I perceived, and somatic practices chosen specifically for your field, so that what shifted stays shifted.",
              "listLabel": "You'll receive",
              "bullets": [
                "A personal field map",
                "Full written field reflection",
                "Somatic practices matched to your field"
              ],
              "note": "🛈 see FAQ",
              "price": "$155",
              "ctaLabel": "Book a Reading",
              "ctaHref": "https://www.paypal.com/ncp/payment/BZBB2PTAPG6GQ",
              "ctaTarget": "_blank",
              "variant": "feature",
              "leadImageUrl": "/images/tenants/resonantweaver/energybody.png",
              "leadImageAlt": "Subtle energy body artwork",
              "leadImageGlow": true,
              "mediaUrl": "",
              "mediaAlt": "",
              "mediaRight": false
            }
          ]
        }
      }
    },
    {
      "id": "sec-quotes-1",
      "type": "rf-testimonials",
      "label": "Testimonials — Resonance Mirror",
      "blocks": [],
      "enabled": true,
      "config": {
        "props": {
          "kicker": "Testimonials",
          "quoteMark": "\"",
          "ruleBelow": true,
          "items": [
            {
              "quote": "So much was spot on. Pretty much everything is true... there's so much that resonated.",
              "attribution": "K., Australia"
            },
            {
              "quote": "Wow, that's beautiful. Spot on. You always amaze me.",
              "attribution": "M, Hawaii"
            },
            {
              "quote": "You have no idea how aligned this is... your channel is excellent.",
              "attribution": "D., New Zealand"
            }
          ]
        }
      }
    },
    {
      "id": "sec-offer-2",
      "type": "rf-offer-card",
      "label": "Offerings 2",
      "blocks": [],
      "enabled": true,
      "config": {
        "props": {
          "columns": 1,
          "heading": "",
          "bulletGlyph": "✦",
          "padTop": 0,
          "padBottom": 25,
          "items": [
            {
              "anchorId": "the-pearl-chamber",
              "title": "The Pearl Chamber",
              "sub": "A weekly holding for one intention",
              "body": "Your intention is placed inside the chamber and held there within 24 hours of purchase, where it is tended daily through meditation, energy work, and spoken enchantment.\n\nThe box found me at a secondhand market in Bulgaria. Inside the lid, a previous owner had written \"Martha\" - a version of my own name. \n\nIt now carries a raw milky quartz cluster from my land, the four primary Usui Reiki symbols, along with your intention.",
              "listLabel": "You'll receive",
              "bullets": [
                "A photograph of your intention in the chamber",
                "Daily intention tending",
                "Gentle field maintenance"
              ],
              "note": "🛈 see FAQ",
              "price": "$11 / week",
              "ctaLabel": "Leave intention",
              "ctaHref": "/pearl-chamber",
              "ctaTarget": "",
              "variant": "feature",
              "leadImageUrl": "/images/tenants/resonantweaver/ReikiBox.png",
              "leadImageAlt": "Pearl Chamber subscription artwork",
              "leadImageGlow": false,
              "mediaUrl": "",
              "mediaAlt": "",
              "mediaRight": false
            }
          ]
        }
      }
    },
    {
      "id": "sec-offer-3",
      "type": "rf-offer-card",
      "label": "Offerings 3",
      "blocks": [],
      "enabled": true,
      "config": {
        "props": {
          "columns": 1,
          "heading": "",
          "bulletGlyph": "✦",
          "padTop": 0,
          "padBottom": 25,
          "items": [
            {
              "anchorId": "pulse-mirror",
              "title": "Pulse Mirror",
              "sub": "A focused read of your field in this moment",
              "body": "Where the Resonance Mirror maps the full terrain, this goes straight to what is most active right now. The core themes moving through your system, what is yours, what isn't. I work with what I find as I find it.\n\nYou'll receive a short written reflection, an energetic healing, and one or two somatic practices to hold the shift.\n\nClean, direct, complete.",
              "listLabel": "You'll receive",
              "bullets": [
                "Written field reflection",
                "Somatic practices matched to your field"
              ],
              "note": "🛈 see FAQ",
              "price": "$55",
              "ctaLabel": "Book a Reading",
              "ctaHref": "https://www.paypal.com/ncp/payment/TKHBAPVB3WQTL",
              "ctaTarget": "_blank",
              "variant": "standard",
              "leadImageUrl": "",
              "leadImageAlt": "",
              "leadImageGlow": false,
              "mediaUrl": "",
              "mediaAlt": "",
              "mediaRight": false
            }
          ]
        }
      }
    },
    {
      "id": "sec-offer-4",
      "type": "rf-offer-card",
      "label": "Offerings 4",
      "blocks": [],
      "enabled": true,
      "config": {
        "props": {
          "columns": 1,
          "heading": "",
          "bulletGlyph": "✦",
          "padTop": 0,
          "padBottom": 25,
          "items": [
            {
              "anchorId": "harmonic-sweep",
              "title": "Harmonic Sweep",
              "sub": "Energetic attunement for spaces",
              "body": "Every space carries its own history. Some of it settles naturally. Some of it doesn't.\n\nThis is a remote reading and clearing of how a space is holding energy right now. What has gathered, what is lingering, and what the space is asking for.\n\nYou receive a written report of what I found, practical suggestions for supporting the shift, and energetic clearing carried out as part of the process. If the space has presences ready to move on, that is handled.",
              "listLabel": "You'll receive",
              "bullets": [
                "Written findings and observations",
                "Practical harmonisation suggestions",
                "Energetic clearing included"
              ],
              "note": "🛈 see FAQ",
              "price": "$77",
              "ctaLabel": "Book a Reading",
              "ctaHref": "https://www.paypal.com/ncp/payment/FLFV8FX5RZP92",
              "ctaTarget": "_blank",
              "variant": "standard",
              "leadImageUrl": "",
              "leadImageAlt": "",
              "leadImageGlow": false,
              "mediaUrl": "",
              "mediaAlt": "",
              "mediaRight": false
            }
          ]
        }
      }
    },
    {
      "id": "sec-quotes-4",
      "type": "rf-testimonials",
      "label": "Testimonials — Harmonic Sweep",
      "blocks": [],
      "enabled": true,
      "config": {
        "props": {
          "kicker": "Testimonials",
          "quoteMark": "\"",
          "ruleBelow": true,
          "items": [
            {
              "quote": "This totally resonates... thank you for sharing your beautiful gift.",
              "attribution": "M., Australia."
            },
            {
              "quote": "Yes, yes and yes... I'm curious to feel the house when I go back. Thank you so much!",
              "attribution": "K., Finland."
            }
          ]
        }
      }
    },
    {
      "id": "sec-faq",
      "type": "rf-accordion",
      "label": "FAQ",
      "blocks": [],
      "enabled": true,
      "config": {
        "props": {
          "heading": "Frequently Asked Questions",
          "lede": "Common queries about the nature of this work.",
          "defaultOpen": -1,
          "look": "panel",
          "centeredHead": true,
          "ruleUnderHead": true,
          "animate": true,
          "exclusive": true,
          "items": [
            {
              "name": "What kind of guidance is this?",
              "body": "The offerings are reflective and interpretive in nature. They include perspectives, awareness, and optional suggestions related to personal experience, embodiment, or environment. Any adjustments or practices suggested, whether somatic or environmental, are invitations, not prescriptions. Resonant Weaver does not provide medical, psychological, or legal advice."
            },
            {
              "name": "How do I work with what I receive?",
              "body": "These offerings support personal sovereignty and discernment. How (or whether) you apply what's offered is entirely your choice and responsibility."
            },
            {
              "name": "Do I need to know Human Design?",
              "body": "No. You can come in with zero background. If Human Design is referenced, it's translated into plain language and grounded takeaways."
            },
            {
              "name": "Are readings remote?",
              "body": "Yes. Readings are completed remotely and shared as a written reflection by email. This allows the work to be done without scheduling or live interaction, and gives you space to receive it in your own time."
            },
            {
              "name": "What do I need to prepare?",
              "body": "You don't need to prepare anything in advance. The work meets your system where it is, and you'll receive simple guidance alongside the reflection."
            },
            {
              "name": "Is this mediumship / channeling?",
              "body": "This work draws on clairsentience and claircognizance as sensing tools. I translate what I receive into grounded reflections and practical suggestions, always aimed at coherence, capacity, and what your system can comfortably integrate now."
            },
            {
              "name": "Is this for everyone?",
              "body": "This work is best suited for people who are interested in exploring their subtle energy body, open to sensing and reflecting on subtle experience, and willing to take an active role in their own process. If you're looking for prediction, diagnosis, or external authority, this may not be the right fit."
            },
            {
              "name": "How long before I receive my reading?",
              "body": "The readings are completed remotely at a dedicated time.  You'll receive a written reflection by email once it's complete. Typically 1-2 business days."
            }
          ]
        }
      }
    },
    {
      "id": "sec-contact",
      "type": "form-live",
      "label": "Contact",
      "blocks": [],
      "enabled": true,
      "config": {
        "props": {
          "formId": "904a1f4d-26bb-42df-b3a2-a16a655fc99d",
          "accent": "",
          "hideHeader": false,
          "maxWidth": 640
        }
      }
    },
    {
      "id": "sec-about",
      "type": "rf-offer-card",
      "label": "About",
      "blocks": [],
      "enabled": true,
      "config": {
        "props": {
          "columns": 1,
          "heading": "",
          "bulletGlyph": "✦",
          "padTop": 0,
          "padBottom": 25,
          "items": [
            {
              "anchorId": "about",
              "title": "Background",
              "sub": "Practice, training, and orientation",
              "body": "I live in a small forest in Sweden, on a homestead we're slowly learning to run. Most things here have been figured out the hard way. Carrying water from a neighbour's well, making firewood, learning to grow food from scratch. It has been a good teacher in paying attention to what's actually there rather than what you expect to find.\n\nI've been drawn to what moves beneath the surface since I was a child. That curiosity became a practice, and the practice became this work. I hold certifications in mediumship, Usui Reiki Master/Teacher, and soul guide work, and I've spent years developing a way of reading energetic fields that is closer to structural mapping than interpretation.\n\nI receive through clairsentience and claircognizance. I feel what is happening in a field directly, in my own system, and translate that into something grounded and usable. I also work with light language, spoken and through movement, when a field needs direct intervention rather than reflection.",
              "listLabel": "",
              "bullets": [],
              "note": "",
              "price": "",
              "ctaLabel": "",
              "ctaHref": "",
              "variant": "compact-media",
              "mediaUrl": "/images/tenants/resonantweaver/About-Portrait.png",
              "mediaAlt": "Portrait of Marthe",
              "mediaPortrait": true
            }
          ]
        }
      }
    }
  ]
}$rwjson$::jsonb);

INSERT INTO _rw_pages VALUES ('writing', 'Writing', true, $rwjson${
  "id": "pm-rw-writing",
  "slug": "writing",
  "title": "Writing",
  "chrome": {
    "navEnabled": true,
    "footerEnabled": true,
    "meta": {
      "description": "Essays, reflections, and field notes from Resonant Weaver, with links to full pieces on Substack.",
      "keywords": [
        "Resonant Weaver writing",
        "Substack essays",
        "energetic writing",
        "field notes",
        "somatic reflections"
      ],
      "ogImage": "/images/tenants/resonantweaver/RW-OG-logo.jpg"
    }
  },
  "sections": [
    {
      "id": "sec-writing-head",
      "type": "rf-media-copy",
      "label": "Writing",
      "blocks": [],
      "enabled": true,
      "config": {
        "props": {
          "imageUrl": "",
          "imageAlt": "",
          "imagePosition": "left",
          "eyebrow": "Writing",
          "eyebrowColor": "accent",
          "heading": "Field notes, essays,",
          "headingLevel": 1,
          "headingAccent": "& reflections.",
          "paragraphs": [
            "A small library for longer pieces from Resonant Weaver. Each entry can hold a short introduction here and open the full article on Substack."
          ],
          "chips": [],
          "ctas": []
        }
      }
    },
    {
      "id": "sec-writing-entries",
      "type": "rf-offer-card",
      "label": "Entries",
      "blocks": [],
      "enabled": true,
      "config": {
        "props": {
          "columns": 2,
          "heading": "",
          "bulletGlyph": "✦",
          "padTop": 0,
          "padBottom": 25,
          "items": [
            {
              "anchorId": "placeholder-1",
              "title": "A place for longer reflections",
              "sub": "Field notes",
              "body": "This page is set up as your on-site writing index. Each card can hold a short introduction here and link outward to the full essay on Substack.",
              "listLabel": "",
              "bullets": [
                "Coming soon",
                "Substack link"
              ],
              "price": "",
              "ctaLabel": "",
              "ctaHref": "",
              "ctaTarget": "",
              "variant": "media",
              "mediaUrl": "/images/tenants/resonantweaver/RW-OG-logo.jpg",
              "mediaAlt": "Abstract Resonant Weaver field guide cover"
            },
            {
              "anchorId": "placeholder-2",
              "title": "How to add a Substack entry",
              "sub": "Setup",
              "body": "Open this page in the studio, duplicate a card, and paste in the article title, excerpt, date, and the full Substack URL.",
              "listLabel": "",
              "bullets": [
                "Ready when you are",
                "Edit in the studio"
              ],
              "price": "",
              "ctaLabel": "",
              "ctaHref": "",
              "ctaTarget": "",
              "variant": "media",
              "mediaUrl": "",
              "mediaAlt": "Resonant Weaver logo cover"
            }
          ]
        }
      }
    }
  ]
}$rwjson$::jsonb);

-- ── insert ─────────────────────────────────────────────────────────────────
-- Null-safe NOT EXISTS on the same tuple the unique index names — the index
-- cannot do this job because a published row carries user_id NULL and NULL is
-- distinct from NULL.
WITH ins AS (
  INSERT INTO public.page_models
    (slug, lang, mode, user_id, deleted_at, title, is_public, in_nav, model_json, updated_at, site)
  SELECT r.slug, 'en', 'published', NULL, NULL, r.title, true, r.in_nav, r.model, now(), 'resonantweaver'
    FROM _rw_pages r
   WHERE NOT EXISTS (
     SELECT 1 FROM public.page_models p
      WHERE p.site = 'resonantweaver' AND p.slug = r.slug AND p.lang = 'en'
        AND p.mode = 'published' AND p.user_id IS NOT DISTINCT FROM NULL
   )
  RETURNING 1
)
SELECT 'pages authored: ' || count(*) FROM ins;

-- ── assertions ─────────────────────────────────────────────────────────────
DO $$
DECLARE
  n int;
  expected constant text[] := ARRAY['home', 'home-classic', 'writing'];
BEGIN
  SELECT count(*) INTO n FROM public.page_models
   WHERE site = 'resonantweaver' AND lang = 'en' AND mode = 'published'
     AND user_id IS NULL AND deleted_at IS NULL AND is_public
     AND slug = ANY(expected);
  IF n <> array_length(expected, 1) THEN
    RAISE EXCEPTION 'assert: expected % pages readable, found %', array_length(expected, 1), n;
  END IF;

  -- Every section names a type the shared catalog renders. A typo is invisible
  -- in SQL and shows up as a blank band — how the homeHero gap presented on
  -- giocoelho.
  --
  -- SCOPED TO THE SLUGS THIS FILE AUTHORS. It used to sweep every published row
  -- of hers while listing only the types THIS file emits, which was true right
  -- up until a sibling migration in this directory authored one more: the
  -- `journey` row (04-journey-row.sql) is `rf-journey`, and this assertion
  -- failed the whole transaction over a row it had not written and had no
  -- opinion about. A file asserts about its own output.
  SELECT count(*) INTO n
    FROM public.page_models p, LATERAL jsonb_array_elements(p.model_json->'sections') s
   WHERE p.site = 'resonantweaver' AND p.mode = 'published'
     AND p.slug = ANY(expected)
     AND s->>'type' NOT IN ('rf-split-hero', 'rf-media-copy', 'rf-door-card', 'rf-offer-card', 'rf-accordion', 'form-live', 'rf-testimonials');
  IF n <> 0 THEN
    RAISE EXCEPTION 'assert: % section(s) name an unexpected type', n;
  END IF;

  -- No path that would resolve against HER app. Only ever caught by a browser
  -- or by this line.
  SELECT count(*) INTO n FROM public.page_models
   WHERE site = 'resonantweaver' AND model_json::text ~ '"/images/(?!tenants/)';
  IF n <> 0 THEN
    RAISE EXCEPTION 'assert: % row(s) carry an app-relative asset path', n;
  END IF;

  -- The contact section points at a form that exists and belongs to her site.
  SELECT count(*) INTO n
    FROM public.page_models p, LATERAL jsonb_array_elements(p.model_json->'sections') s
   WHERE p.site = 'resonantweaver' AND s->>'type' = 'form-live'
     AND NOT EXISTS (
       SELECT 1 FROM public.forms f JOIN public.villager_sites v ON v.id = f.site_id
        WHERE f.id = (s->'config'->'props'->>'formId')::uuid
          AND v.subdomain = 'resonantweaver' AND f.status = 'published'
     );
  IF n <> 0 THEN
    RAISE EXCEPTION 'assert: % form section(s) point at no published form of hers', n;
  END IF;

  -- Copy the migration made untrue must not come back. Each of these named a
  -- file in her repo as the way to edit this page; the studio is that way now.
  SELECT count(*) INTO n FROM public.page_models
   WHERE site = 'resonantweaver' AND strpos(model_json::text, 'Open `src/data/writing/articles.ts`, duplicate an entry, paste in the article title, excerpt, date, and full Substack URL in `href`.') > 0;
  IF n <> 0 THEN
    RAISE EXCEPTION 'assert: superseded copy is back — the file it names stops being the source of this page at cutover';
  END IF;

  SELECT count(*) INTO n FROM public.page_models
   WHERE site = 'resonantweaver' AND strpos(model_json::text, 'Edit locally') > 0;
  IF n <> 0 THEN
    RAISE EXCEPTION 'assert: superseded copy is back — the same instruction in the card''s meta line';
  END IF;

  RAISE NOTICE 'assertions passed';
END $$;

SELECT slug, title, is_public, in_nav,
       jsonb_array_length(model_json->'sections') AS sections
  FROM public.page_models
 WHERE site = 'resonantweaver' AND mode = 'published' AND user_id IS NULL
 ORDER BY slug;

COMMIT;
