-- 07-chrome.sql — GENERATED by sql/resonantweaver-migration/gen-chrome-rows.mjs.
-- DO NOT HAND-EDIT: re-running the generator overwrites it, and every value in
-- here is guarded against resonantweaver.com's own source.
--
-- PHASE 2 of PIXEL-PARITY-PLAN — the chrome. She had NO nav or footer row at
-- all, so the pooled renderer derived a bar from her site record. That is
-- literally Marthe's "Menu is different", and it is one fix worth twenty-three
-- pages, because chrome is on every one of them.
--
-- Each row is a single `block` layer pointing at a catalog entry — `rf-pill-nav`
-- mounts the SHARED PillNav her own app mounts (it was generalised out of this
-- site), and `rf-site-footer` is her footer's CSS transcribed breakpoint for
-- breakpoint. Nothing is a hand-measured replica.
--
-- THE FRAME IS A PLAIN FLOW FRAME OF HEIGHT ZERO, NOT A CHROME BAND. Her nav is
-- `position: fixed` and reserves no height; a `chromeBehavior:'fixed'` band pads
-- `body` by its own height and would push every page down by the height of a bar
-- that was never in the flow. `grow` makes the frame auto-height with
-- overflow visible, and a fixed child is out of flow, so it measures zero.
--
-- RE-RUNNABLE, AND IT UPDATES — same posture as 01-theme.sql. A re-run DISCARDS
-- studio edits to these two keys; the plan-17 capture trigger records the change
-- so it is visible in Client Versions and revertible, but do not re-run this
-- after Marthe starts editing her own chrome.
--
--   psql -v ON_ERROR_STOP=1 -d tgv_db -f sql/resonantweaver-migration/07-chrome.sql

\set ON_ERROR_STOP on

BEGIN;

SELECT set_config('app.actor', 'migration:resonantweaver-07-chrome', true);

-- A BEFORE-PICTURE, taken before a single write, so assertion (f) can ask what
-- THIS RUN changed rather than what changed recently. The first version asked
-- for chrome rows with `updated_at > now() - interval '1 minute'` and failed on
-- its first real run — not because it wrote outside its site, but because the
-- four PLATFORM chrome rows carry timestamps four and a half hours in the
-- FUTURE (a UTC-vs-local write, predating this file by days). A clock window is
-- not authorship, and a guard that fires on somebody else's bad timestamp is a
-- guard people learn to delete.
CREATE TEMP TABLE rw_chrome_before ON COMMIT DROP AS
SELECT key, lang, mode, user_id, site, data, updated_at
  FROM public.content_overrides
 WHERE key IN ('navLayers','footerLayers')
   AND site IS DISTINCT FROM 'resonantweaver';

-- ── navLayers ─────────────────────────────────────────────────────────────
INSERT INTO public.content_overrides (key, lang, mode, user_id, data, updated_at, site)
SELECT 'navLayers', 'en', 'published', NULL, $rwchrome${
  "layers": [
    {
      "id": "rw-nav",
      "type": "block",
      "name": "Pill nav",
      "grow": true,
      "box": {
        "desktop": {
          "x": 0,
          "y": 0,
          "w": 0,
          "h": 0,
          "rot": 0,
          "hidden": false
        }
      },
      "blockRef": {
        "type": "rf-pill-nav",
        "props": {
          "logoSrc": "/images/tenants/resonantweaver/Small-Logo-RW-2026.svg",
          "logoAlt": "Resonant Weaver home",
          "homeHref": "/",
          "items": [
            {
              "label": "Starseed",
              "href": "/starseed/"
            },
            {
              "label": "Sun Walk",
              "href": "/sun-walk/"
            },
            {
              "label": "Contact",
              "href": "/#contact"
            },
            {
              "label": "Login",
              "href": "/login/"
            }
          ],
          "accent": "183, 138, 119",
          "fontRole": "mono",
          "navId": "rw-sitenav"
        }
      }
    }
  ],
  "frame": {
    "desktop": {
      "h": 0
    }
  }
}$rwchrome$::jsonb, now(), 'resonantweaver'
 WHERE NOT EXISTS (
   SELECT 1 FROM public.content_overrides
    WHERE site = 'resonantweaver' AND key = 'navLayers'
      AND lang = 'en' AND mode = 'published'
      AND user_id IS NOT DISTINCT FROM NULL
 );

UPDATE public.content_overrides
   SET data = $rwchrome${
  "layers": [
    {
      "id": "rw-nav",
      "type": "block",
      "name": "Pill nav",
      "grow": true,
      "box": {
        "desktop": {
          "x": 0,
          "y": 0,
          "w": 0,
          "h": 0,
          "rot": 0,
          "hidden": false
        }
      },
      "blockRef": {
        "type": "rf-pill-nav",
        "props": {
          "logoSrc": "/images/tenants/resonantweaver/Small-Logo-RW-2026.svg",
          "logoAlt": "Resonant Weaver home",
          "homeHref": "/",
          "items": [
            {
              "label": "Starseed",
              "href": "/starseed/"
            },
            {
              "label": "Sun Walk",
              "href": "/sun-walk/"
            },
            {
              "label": "Contact",
              "href": "/#contact"
            },
            {
              "label": "Login",
              "href": "/login/"
            }
          ],
          "accent": "183, 138, 119",
          "fontRole": "mono",
          "navId": "rw-sitenav"
        }
      }
    }
  ],
  "frame": {
    "desktop": {
      "h": 0
    }
  }
}$rwchrome$::jsonb, updated_at = now()
 WHERE site = 'resonantweaver' AND key = 'navLayers'
   AND lang = 'en' AND mode = 'published'
   AND user_id IS NOT DISTINCT FROM NULL
   AND data IS DISTINCT FROM $rwchrome${
  "layers": [
    {
      "id": "rw-nav",
      "type": "block",
      "name": "Pill nav",
      "grow": true,
      "box": {
        "desktop": {
          "x": 0,
          "y": 0,
          "w": 0,
          "h": 0,
          "rot": 0,
          "hidden": false
        }
      },
      "blockRef": {
        "type": "rf-pill-nav",
        "props": {
          "logoSrc": "/images/tenants/resonantweaver/Small-Logo-RW-2026.svg",
          "logoAlt": "Resonant Weaver home",
          "homeHref": "/",
          "items": [
            {
              "label": "Starseed",
              "href": "/starseed/"
            },
            {
              "label": "Sun Walk",
              "href": "/sun-walk/"
            },
            {
              "label": "Contact",
              "href": "/#contact"
            },
            {
              "label": "Login",
              "href": "/login/"
            }
          ],
          "accent": "183, 138, 119",
          "fontRole": "mono",
          "navId": "rw-sitenav"
        }
      }
    }
  ],
  "frame": {
    "desktop": {
      "h": 0
    }
  }
}$rwchrome$::jsonb;

-- ── footerLayers ─────────────────────────────────────────────────────────────
INSERT INTO public.content_overrides (key, lang, mode, user_id, data, updated_at, site)
SELECT 'footerLayers', 'en', 'published', NULL, $rwchrome${
  "layers": [
    {
      "id": "rw-footer",
      "type": "block",
      "name": "Site footer",
      "grow": true,
      "box": {
        "desktop": {
          "x": 0,
          "y": 0,
          "w": 0,
          "h": 0,
          "rot": 0,
          "hidden": false
        }
      },
      "blockRef": {
        "type": "rf-site-footer",
        "props": {
          "line": "© 2026 Resonant Weaver. All rights reserved.",
          "creditText": "Powered by",
          "creditLabel": "Tiny Global Village LLC™",
          "creditHref": "https://tinyglobalvillage.com",
          "ink": "hsla(40, 20%, 90%, 0.72)",
          "linkColor": "hsla(40, 20%, 90%, 0.82)",
          "linkHoverColor": "#E8E5DA",
          "focusColor": "rgba(72, 210, 185, 0.7)",
          "borderColor": "rgba(255, 255, 255, 0.03)",
          "bg": "transparent",
          "fontRole": "mono",
          "anchorId": "footer"
        }
      }
    }
  ],
  "frame": {
    "desktop": {
      "h": 0
    }
  }
}$rwchrome$::jsonb, now(), 'resonantweaver'
 WHERE NOT EXISTS (
   SELECT 1 FROM public.content_overrides
    WHERE site = 'resonantweaver' AND key = 'footerLayers'
      AND lang = 'en' AND mode = 'published'
      AND user_id IS NOT DISTINCT FROM NULL
 );

UPDATE public.content_overrides
   SET data = $rwchrome${
  "layers": [
    {
      "id": "rw-footer",
      "type": "block",
      "name": "Site footer",
      "grow": true,
      "box": {
        "desktop": {
          "x": 0,
          "y": 0,
          "w": 0,
          "h": 0,
          "rot": 0,
          "hidden": false
        }
      },
      "blockRef": {
        "type": "rf-site-footer",
        "props": {
          "line": "© 2026 Resonant Weaver. All rights reserved.",
          "creditText": "Powered by",
          "creditLabel": "Tiny Global Village LLC™",
          "creditHref": "https://tinyglobalvillage.com",
          "ink": "hsla(40, 20%, 90%, 0.72)",
          "linkColor": "hsla(40, 20%, 90%, 0.82)",
          "linkHoverColor": "#E8E5DA",
          "focusColor": "rgba(72, 210, 185, 0.7)",
          "borderColor": "rgba(255, 255, 255, 0.03)",
          "bg": "transparent",
          "fontRole": "mono",
          "anchorId": "footer"
        }
      }
    }
  ],
  "frame": {
    "desktop": {
      "h": 0
    }
  }
}$rwchrome$::jsonb, updated_at = now()
 WHERE site = 'resonantweaver' AND key = 'footerLayers'
   AND lang = 'en' AND mode = 'published'
   AND user_id IS NOT DISTINCT FROM NULL
   AND data IS DISTINCT FROM $rwchrome${
  "layers": [
    {
      "id": "rw-footer",
      "type": "block",
      "name": "Site footer",
      "grow": true,
      "box": {
        "desktop": {
          "x": 0,
          "y": 0,
          "w": 0,
          "h": 0,
          "rot": 0,
          "hidden": false
        }
      },
      "blockRef": {
        "type": "rf-site-footer",
        "props": {
          "line": "© 2026 Resonant Weaver. All rights reserved.",
          "creditText": "Powered by",
          "creditLabel": "Tiny Global Village LLC™",
          "creditHref": "https://tinyglobalvillage.com",
          "ink": "hsla(40, 20%, 90%, 0.72)",
          "linkColor": "hsla(40, 20%, 90%, 0.82)",
          "linkHoverColor": "#E8E5DA",
          "focusColor": "rgba(72, 210, 185, 0.7)",
          "borderColor": "rgba(255, 255, 255, 0.03)",
          "bg": "transparent",
          "fontRole": "mono",
          "anchorId": "footer"
        }
      }
    }
  ],
  "frame": {
    "desktop": {
      "h": 0
    }
  }
}$rwchrome$::jsonb;

-- ── assertions ───────────────────────────────────────────────────────────
-- Each one is a thing that, if false, means resonantweaver.com serves somebody
-- else's chrome — which is the whole defect this file exists to close.
DO $$
DECLARE n int; v text;
BEGIN
  -- (a) both rows exist, and each carries exactly one block layer pointing at
  --     the entry it is supposed to.
  SELECT count(*) INTO n FROM public.content_overrides
   WHERE site = 'resonantweaver' AND lang = 'en' AND mode = 'published'
     AND user_id IS NULL AND key IN ('navLayers','footerLayers');
  IF n <> 2 THEN RAISE EXCEPTION 'assert: expected 2 chrome rows, found %', n; END IF;

  SELECT c.data->'layers'->0->'blockRef'->>'type' INTO v FROM public.content_overrides c
   WHERE c.site = 'resonantweaver' AND c.key = 'navLayers' AND c.lang = 'en'
     AND c.mode = 'published' AND c.user_id IS NULL;
  IF v IS DISTINCT FROM 'rf-pill-nav' THEN
    RAISE EXCEPTION 'assert: navLayers points at %, not rf-pill-nav', coalesce(v, '<null>');
  END IF;

  SELECT c.data->'layers'->0->'blockRef'->>'type' INTO v FROM public.content_overrides c
   WHERE c.site = 'resonantweaver' AND c.key = 'footerLayers' AND c.lang = 'en'
     AND c.mode = 'published' AND c.user_id IS NULL;
  IF v IS DISTINCT FROM 'rf-site-footer' THEN
    RAISE EXCEPTION 'assert: footerLayers points at %, not rf-site-footer', coalesce(v, '<null>');
  END IF;

  -- (b) the layer GROWS and the frame is not a chrome band. Without both, the
  --     frame clips to a fixed height and the nav is invisible, or it pads body
  --     and every page moves down.
  SELECT count(*) INTO n FROM public.content_overrides c
   WHERE c.site = 'resonantweaver' AND c.key IN ('navLayers','footerLayers')
     AND c.lang = 'en' AND c.mode = 'published' AND c.user_id IS NULL
     AND (c.data->'layers'->0->>'grow') = 'true'
     AND c.data->'frame'->>'mode' IS NULL
     AND c.data->'frame'->>'chromeBehavior' IS NULL;
  IF n <> 2 THEN
    RAISE EXCEPTION 'assert: expected 2 growing flow frames, found %', n;
  END IF;

  -- (c) the logo points at HQ's tenant asset dir. Her own app-relative path
  --     resolves against a public dir the pooled renderer does not have, and a
  --     404 there is a nav with no brand mark on every page.
  SELECT c.data->'layers'->0->'blockRef'->'props'->>'logoSrc' INTO v
    FROM public.content_overrides c
   WHERE c.site = 'resonantweaver' AND c.key = 'navLayers' AND c.lang = 'en'
     AND c.mode = 'published' AND c.user_id IS NULL;
  IF v IS DISTINCT FROM '/images/tenants/resonantweaver/Small-Logo-RW-2026.svg' THEN
    RAISE EXCEPTION 'assert: nav logo is %', coalesce(v, '<null>');
  END IF;

  -- (d) no nav href carries a locale prefix. Her app hides the default locale,
  --     so `/en/starseed` 307s there and 404s here — a prefixed link would cost
  --     every visitor a redirect on every click, or break outright.
  SELECT count(*) INTO n FROM public.content_overrides c,
       LATERAL jsonb_array_elements(c.data->'layers'->0->'blockRef'->'props'->'items') i
   WHERE c.site = 'resonantweaver' AND c.key = 'navLayers' AND c.lang = 'en'
     AND c.mode = 'published' AND c.user_id IS NULL
     AND (i->>'href') ~ '^/(en|no)(/|$)';
  IF n <> 0 THEN RAISE EXCEPTION 'assert: % nav href(s) carry a locale prefix', n; END IF;

  -- (e) her four links, in her order.
  SELECT count(*) INTO n FROM public.content_overrides c
   WHERE c.site = 'resonantweaver' AND c.key = 'navLayers' AND c.lang = 'en'
     AND c.mode = 'published' AND c.user_id IS NULL
     AND jsonb_array_length(c.data->'layers'->0->'blockRef'->'props'->'items') = 4;
  IF n <> 1 THEN RAISE EXCEPTION 'assert: nav does not carry exactly 4 links'; END IF;

  -- (f) nothing else on the fleet moved. Chrome is per-site; a changed row keyed
  --     to another tenant, or to the platform, would mean this file wrote outside
  --     its own site. Compared against the before-picture taken above, so it
  --     measures what THIS TRANSACTION did and nothing else.
  SELECT count(*) INTO n FROM (
    (SELECT key, lang, mode, user_id, site, data, updated_at FROM rw_chrome_before
      EXCEPT ALL
     SELECT key, lang, mode, user_id, site, data, updated_at
       FROM public.content_overrides
      WHERE key IN ('navLayers','footerLayers') AND site IS DISTINCT FROM 'resonantweaver')
    UNION ALL
    (SELECT key, lang, mode, user_id, site, data, updated_at
       FROM public.content_overrides
      WHERE key IN ('navLayers','footerLayers') AND site IS DISTINCT FROM 'resonantweaver'
      EXCEPT ALL
     SELECT key, lang, mode, user_id, site, data, updated_at FROM rw_chrome_before)
  ) d;
  IF n <> 0 THEN RAISE EXCEPTION 'assert: this run changed % chrome row(s) outside resonantweaver', n; END IF;

  RAISE NOTICE 'assertions passed — nav and footer are resonantweaver''s own';
END $$;

COMMIT;
